### ISSUE TITLE
mask rcnn训练报错：generate_mask_labels raises an exception

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/PaddleDetection#1624]
环境：paddle1.7.1+ paddleDetection/ release:0.2;
nvidia GPU P40 
多机训练报错，报错信息如下，请问是什么原因？

```
I1026 20:18:17.458163   147 parallel_executor.cc:440] The Program will be executed on CUDA using ParallelExecutor, 1 cards are used, so 1 programs are executed in parallel.
paddle-job-657863-1-worker-5:147:147 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.1.80<0>
paddle-job-657863-1-worker-5:147:147 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).

paddle-job-657863-1-worker-5:147:147 [0] misc/ibvwrap.cu:63 NCCL WARN Failed to open libibverbs.so[.1]
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO comm 0x7f927c0351d0 rank 5 nranks 6 cudaDev 0 nvmlDev 0
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO include/net.h:24 -> 2
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO CUDA Dev 0[0], Socket NIC distance :  SOC
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO include/net.h:24 -> 2
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO Ring 00 : 4 -> 5 [receive] via NET/Socket/0
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO Ring 00 : 5 -> 0 [send] via NET/Socket/0
paddle-job-657863-1-worker-5:147:250 [0] NCCL INFO comm 0x7f927c0351d0 rank 5 nranks 6 cudaDev 0 nvmlDev 0 - Init COMPLETE
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO comm 0x7f927c03cf20 rank 5 nranks 6 cudaDev 0 nvmlDev 0
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO Could not find real path of /sys/class/net/eth0/device
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO include/net.h:24 -> 2
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO Ring 00 : 4 -> 5 [receive] via NET/Socket/0
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO Ring 00 : 5 -> 0 [send] via NET/Socket/0
paddle-job-657863-1-worker-5:147:253 [0] NCCL INFO comm 0x7f927c03cf20 rank 5 nranks 6 cudaDev 0 nvmlDev 0 - Init COMPLETE
I1026 20:18:33.160753   147 build_strategy.cc:365] SeqOnlyAllReduceOps:1, num_trainers:6
I1026 20:18:33.278121   147 parallel_executor.cc:307] Inplace strategy is enabled, when build_strategy.enable_inplace = True
I1026 20:18:33.306521   147 parallel_executor.cc:375] Garbage collection strategy is enabled, when FLAGS_eager_delete_tensor_gb = 0
W1026 20:18:33.390079   257 operator.cc:181] generate_mask_labels raises an exception std::bad_alloc, std::bad_alloc
F1026 20:18:33.390199   257 exception_holder.h:37] std::exception caught, std::bad_alloc
*** Check failure stack trace: ***
    @     0x7f930d135fed  google::LogMessage::Fail()
    @     0x7f930d139a9c  google::LogMessage::SendToLog()
    @     0x7f930d135b13  google::LogMessage::Flush()
    @     0x7f930d13afae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f930f5ff748  paddle::framework::details::ExceptionHolder::Catch()
    @     0x7f930f6aab6e  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOpSync()
    @     0x7f930f6a977f  paddle::framework::details::FastThreadedSSAGraphExecutor::RunOp()
    @     0x7f930f6a9a44  _ZNSt17_Function_handlerIFvvESt17reference_wrapperISt12_Bind_simpleIFS1_ISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS6_12OpHandleBaseESt6atomicIiESt4hashISA_ESt8equal_toISA_ESaISt4pairIKSA_SC_EEESA_RKSt10shared_ptrINS5_13BlockingQueueImEEEEUlvE_vEEEvEEEE9_M_invokeERKSt9_Any_data
    @     0x7f930d18ed43  std::_Function_handler<>::_M_invoke()
    @     0x7f930cf1e537  std::__future_base::_State_base::_M_do_set()
    @     0x7f93ad91aa99  __pthread_once_slow
    @     0x7f930f6a4f32  _ZNSt13__future_base11_Task_stateISt5_BindIFZN6paddle9framework7details28FastThreadedSSAGraphExecutor10RunOpAsyncEPSt13unordered_mapIPNS4_12OpHandleBaseESt6atomicIiESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SA_EEES8_RKSt10shared_ptrINS3_13BlockingQueueImEEEEUlvE_vEESaIiEFvvEE6_M_runEv
    @     0x7f930cf20764  _ZZN10ThreadPoolC1EmENKUlvE_clEv
    @     0x7f935c255421  execute_native_thread_routine_compat
    @     0x7f93ad9136ba  start_thread
    @     0x7f93ad64941d  clone
    @              (nil)  (unknown)

```

**Comment by yghstill** [comment]
@ellinyang 请更新Paddle到1.8以上，并使用paddleDetection的release/0.4版本再试下

**Comment by ellinyang** [comment]
> @ellinyang 请更新Paddle到1.8以上，并使用paddleDetection的release/0.4版本再试下

线上问题，涉及面较大，短期内较难升级PaddleDetection。请问这个报错有可能的原因吗？我们针对性排查一下。

**Comment by ellinyang** [comment]
> @ellinyang 请更新Paddle到1.8以上，并使用paddleDetection的release/0.4版本再试下

paddleDetection的release/0.4+ paddle1.8.4 单机线下复现了错误

**Comment by ellinyang** [comment]
> > @ellinyang 请更新Paddle到1.8以上，并使用paddleDetection的release/0.4版本再试下
> 
> paddleDetection的release/0.4+ paddle1.8.4 单机线下复现了错误
在paddledetection同学的协助下，该问题已解决。
训练使用coco的数据格式，其中部分标注有问题：目标对象有gt_bboxes，但是gt_mask为空，所以mask和bboxes长度不匹配，导致训练失败。
通过前置的数据清洗，将空的分割标注对应的bboxes同时去除掉后，训练、评估正常。
感谢paddle的同学～

**Comment by ellinyang** [comment]
在paddledetection同学的协助下，该问题已解决。
训练使用coco的数据格式，其中部分标注有问题：目标对象有gt_bboxes，但是gt_mask为空，所以mask和bboxes长度不匹配，导致训练失败。
通过前置的数据清洗，将空的分割标注对应的bboxes同时去除掉后，训练、评估正常。
感谢paddle的同学～
