### ISSUE TITLE
单gpu 多进程报错

### ISSUE THREAD

**Issue by habout632** [PaddlePaddle/PaddleDetection#2241]
我在用flask写的接口的时候， 使用multiprocessing处理多个图片 提示如下错误
OSError: (External)  Cuda error(3), initialization error.
  [Advise: The API call failed because the CUDA driver and runtime could not be initialized. ] (at /paddle/paddle/fluid/platform/gpu_info.cc:200)

**Comment by habout632** [comment]
![Screenshot from 2021-02-20 16-35-46](https://user-images.githubusercontent.com/3166070/108589570-e2f79900-7399-11eb-9cf4-3294c3964205.png)

**Comment by habout632** [comment]
这是什么原因呢

**Comment by qingqing01** [comment]
@habout632 

> CUDA driver and runtime could not be initialized

单独进行Paddle预测正确吗？ 看样子封装时，Paddle相关初始化没有正确设置，您是调用Python预测吗？

**Comment by habout632** [comment]
单独调用是正确的 变成多进程就报错了

**Comment by liuhuiCNN** [comment]
请参考这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/native_infer.html#duoxianchengyuce

**Comment by heavengate** [comment]
您好，鉴于问题已经解决，当前issue关闭，如果还有问题可以reopen这个issue~

**Comment by OneOneLiu** [comment]
> 请参考这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/05_inference_deployment/inference/native_infer.html#duoxianchengyuce

你好,我也遇到了这个问题,我这边上面的链接打开是会自动跳转到paddle教程首页,没有问题相关信息,请问应该去哪里找呢.

**Comment by sicklife** [comment]
我也遇到了这个问题。但是莫名其妙地解决了。似乎是和引用paddle的顺序有关系。

**Comment by cpene1** [comment]
Check this:

https://github.com/PaddlePaddle/PaddleOCR/issues/3070#issuecomment-857698911

**Comment by NLPOR** [comment]
我也遇到了同样的问题，不使用multiprocess跑没问题，使用multiprocess.process多进程的时候就报同样的错误，表示没有看到怎么解决啊，怎么就closed了呢

**Comment by futureisatyourhand** [comment]
> 我也遇到了同样的问题，不使用multiprocess跑没问题，使用multiprocess.process多进程的时候就报同样的错误，表示没有看到怎么解决啊，怎么就closed了呢

我也遇到这个问题了，你怎么解决的哦

**Comment by sallenhandong** [comment]
> > 我也遇到了同样的问题，不使用multiprocess跑没问题，使用multiprocess.process多进程的时候就报同样的错误，表示没有看到怎么解决啊，怎么就closed了呢
> 
> 我也遇到这个问题了，你怎么解决的哦

同问

**Comment by NLPOR** [comment]
与paddle相关的初始化模块不要在主进程import，全部在子进程中进行import就可以

**Comment by yunkchen** [comment]
> 与paddle相关的初始化模块不要在主进程import，全部在子进程中进行import就可以

子进程里import，还是一样错误

**Comment by Essence9999** [comment]
> 这是什么原因呢

同样的问题，楼主解决了吗？

**Comment by Essence9999** [comment]
> > 与paddle相关的初始化模块不要在主进程import，全部在子进程中进行import就可以
> 
> 子进程里import，还是一样错误

同样的问题，楼主解决了吗？

**Comment by yunkchen** [comment]
> > > 与paddle相关的初始化模块不要在主进程import，全部在子进程中进行import就可以
> > 
> > 
> > 子进程里import，还是一样错误
> 
> 同样的问题，楼主解决了吗？

昨天解决了；把import paddle放到子进程里，注意其它imort 的模块是否在内部也初始化了paddle，如果有也需要放到子进程里

**Comment by futureisatyourhand** [comment]
> > > 我也遇到了同样的问题，不使用multiprocess跑没问题，使用multiprocess.process多进程的时候就报同样的错误，表示没有看到怎么解决啊，怎么就closed了呢
> > 
> > 
> > 我也遇到这个问题了，你怎么解决的哦
> 
> 同问
确实得每个子进程里面单独用gpu

**Comment by yanzheng636** [comment]
使用forkserver 方式运行

**Comment by simon-sxx** [comment]
@yunkchen 请问主进程和子进程都用到了paddle怎么办呀，

>

**Comment by lmw0320** [comment]
这个问题，貌似至今都没法解决啊？？
我也遇到了类似情况，使用http服务，主动调用多进程，结果是发现导包报错
![1](https://user-images.githubusercontent.com/37755235/175437522-afbe21f2-3e5c-4ca1-b4e4-17174e90ef5b.png)

**Comment by hotvscool** [comment]
参考这篇文章，是可以多进程的
https://blog.csdn.net/qq_45779334/article/details/122024343

**Comment by fantuanliu** [comment]
报错+1，批量数据识别，推理的时候报这个错误，请问是什么原因
相同配置的服务器，一台报错，一台不报错
