### ISSUE TITLE
重新安装英伟达官方的系统，jetson xavier nx 出现 "no kernel image"问题，迫切希望哪位大佬能帮帮忙！

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2359]
![image](https://user-images.githubusercontent.com/32217129/111243401-fd8cfd00-863b-11eb-8714-89b0110ea982.png)
问题 描述如上，包含命令，就是官方的测试用例。
硬件：jetson xavier nx
系统：jetpack 4.5.1（最新）
paddlepaddle：gpu_2.0.0

这个问题困扰很久了，实在不知道怎么办？迫切希望哪位大佬能帮帮忙！非常感谢！！！

**Comment by jerrywgz** [comment]
可以先确认下paddle是否正确安装，
“”“
import paddle
paddle.utils.run_check()
”“”

**Comment by liuhuiCNN** [comment]
请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。

**Comment by dengxinlong** [comment]
> 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。
1. 下面截图是 import paddle.fluid as fluid 的结果：
![image](https://user-images.githubusercontent.com/32217129/111266579-b3b90c80-8665-11eb-8201-668aa6c7f965.png)
2. 下面截图是 运行 fluid.install_check.run_check() 的结果：
![image](https://user-images.githubusercontent.com/32217129/111267104-7608b380-8666-11eb-8fa1-f567920b461d.png)
3. 下面截图是运行 python ppdet/modeling/tests/test_architectures.py的结果：
![image](https://user-images.githubusercontent.com/32217129/111267263-b0725080-8666-11eb-97b5-e01a06f6e15d.png)

从最后的结果上 来看，是通过了测试最后的 test_architectures.py的测试用例，但是前面run_check出现的问题，还是通过了，我就不太确定了。

**Comment by dengxinlong** [comment]
在运行 fluid.install_check.run_check() 的时候，出现的错误就是：
![image](https://user-images.githubusercontent.com/32217129/111282602-241d5900-8679-11eb-923f-5c2d81946b79.png)
目前已知的就是可能算力不匹配。

**Comment by dengxinlong** [comment]
> 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。

因为我就是在安装完成之后测试官方用例的时候出现的问题，所以才来请教你们，真的非常迫切啊。。。。。

**Comment by dengxinlong** [comment]
> 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断

**Comment by dengxinlong** [comment]
> 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。

**Comment by liuhuiCNN** [comment]
> > 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。
> 
> 因为我就是在安装完成之后测试官方用例的时候出现的问题，所以才来请教你们，真的非常迫切啊。。。。。

（1）请确认设备安装的CUDA版本和安装的paddle需要的CUDA版本是否一致；
（2）paddle官网提供一些情况下的 whl 包：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html
（3）如果官网没有提供适合设备的whl包，需要自行编译：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
（4）如果还有问题，请提供详细的版本说明：硬件设备型号、设备系统、CUDA版本，安装的Paddle版本(可以详细说明安装过程)，我们好复现您的问题，谢谢~

**Comment by dengxinlong** [comment]
> > > 请确认一下安装的系统是否正常吗，可以通过CUDA官方示例是否可以跑通来判断。
> > 
> > 
> > 因为我就是在安装完成之后测试官方用例的时候出现的问题，所以才来请教你们，真的非常迫切啊。。。。。
> 
> （1）请确认设备安装的CUDA版本和安装的paddle需要的CUDA版本是否一致；
> （2）paddle官网提供一些情况下的 whl 包：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html
> （3）如果官网没有提供适合设备的whl包，需要自行编译：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
> （4）如果还有问题，请提供详细的版本说明：硬件设备型号、设备系统、CUDA版本，安装的Paddle版本(可以详细说明安装过程)，我们好复现您的问题，谢谢~

因为你们官网中只有这两个安装包

**Comment by jerrywgz** [comment]
从log来看你这边的环境确实是paddle提供的whl包中没有覆盖到的，关于CUDA版本问题，这个如果单卡没有问题的应该就不会有太大问题；如果是多卡出错的话也可能是NCCL安装问题导致的，可以参考上面的安装文档check下NCCL的安装

另外比较推荐使用飞桨提供的官方docker，里面的环境是经过验证的

**Comment by dengxinlong** [comment]
> 从log来看你这边的环境确实是paddle提供的whl包中没有覆盖到的，关于CUDA版本问题，这个如果单卡没有问题的应该就不会有太大问题；如果是多卡出错的话也可能是NCCL安装问题导致的，可以参考上面的安装文档check下NCCL的安装
> 
> 另外比较推荐使用飞桨提供的官方docker，里面的环境是经过验证的

关于我这边的cuda环境就是jetson xavier nx 官方的jetpack4.5.1所提供的环境，它的其他版本的jetpack也都是这个环境。
我先查一下NCCL吧。关于  考上面的安装文档check下NCCL的安装 的链接有吗？如果实在不行，我尝试源码安装吧

**Comment by dengxinlong** [comment]
> 从log来看你这边的环境确实是paddle提供的whl包中没有覆盖到的，关于CUDA版本问题，这个如果单卡没有问题的应该就不会有太大问题；如果是多卡出错的话也可能是NCCL安装问题导致的，可以参考上面的安装文档check下NCCL的安装
> 
> 另外比较推荐使用飞桨提供的官方docker，里面的环境是经过验证的

对了，您刚才提到飞桨官方的docker，有相关的链接吗？谢谢！！

**Comment by jerrywgz** [comment]
nccl的安装文档，这里提供了centos和ubuntu的，也可以到nividia官网看下 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#cpu-gpu

官网docker使用文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

**Comment by dengxinlong** [comment]
> nccl的安装文档，这里提供了centos和ubuntu的，也可以到nividia官网看下 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#cpu-gpu
> 
> 官网docker使用文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html

好的，非常感谢您的回复！

**Comment by dengxinlong** [comment]
不好意思，问题已经解决了，感谢官方的耐心回复。说一下：

numpy包之前安装的是 1.19，如果直接使用 pip3 install numpy，后面导入numpy包的时候会发生非法指令错误，我安装的是numpy 1.17
记得源码编译安装 nccl，https://blog.csdn.net/fuck_hang/article/details/108704045 这个链接中有怎么源码编译安装paddle，里面也有源码编译安装nccl，还有就是使用虚拟环境来使用。官方的教程中的源码安装paddle中有提到安装 virtualenvwrapper，但是就是提到了，如果不会的，就直接百度相关的教程，然后就是直接使用官方的包：
![image](https://user-images.githubusercontent.com/32217129/111565301-129d9380-87d6-11eb-91eb-056eec8620cc.png)

我安装的 是 箭头指向的。画 x 的我也测试了一下，发现不符合我目前的环境。这里的话只是我的环境，你的环境可能不太一样，针对 jetson xavier nx。
镜像：jetpack 4.5.1，cuda 和 cudnn 都是官方镜像自带的。
