### ISSUE TITLE
maskRcnn推理内存溢出

### ISSUE THREAD

**Issue by hymanzhu1983** [PaddlePaddle/PaddleDetection#2420]
输入到maskrcnn推理程序的图片如果包含全白色的图片，会导致程序崩溃，怀疑网络在检测不出任何目标的情况下会出问题。复现步骤如下：
1.下载https://paddlemodels.bj.bcebos.com/object_detection/mask_rcnn_r50_1x.tar模型，解压
2. 用命令python tools/export_model.py  -c configs/mask_rcnn_r50_1x.yml --output_dir=inference_model -o weights=PaddleDetection-release-2.0-beta/output/mask_rcnn_r50_1x 转换成deploy的模型格式。
3. 修改deploy/python/infer.py文件，使得它可以推理文件夹里所有的图片。增加的函数类似

```
def predict_image(detector):
    for img_file in os.listdir(FLAGS.image_dir):
        img_file = os.path.join(FLAGS.image_dir, img_file)
        results = detector.predict(img_file, FLAGS.threshold)
        visualize(
            img_file,
            results,
            detector.config.labels,
            mask_resolution=detector.config.mask_resolution,
            output_dir=FLAGS.output_dir,
            threshold=FLAGS.threshold)
```
4. 在图片文件夹中放入普通街景图片，同时混入几张全白色图片，运行命令：
python deploy/python/infer.py --model_dir=inference_model/mask_rcnn_r50_1x --image_dir=./image --use_gpu=True
在推理几张图片后程序崩溃：

```
-----------  Running Arguments -----------
image_dir: /home/sy/work/ocr_car/PaddleDetection/bill_image
model_dir: inference_model/mask_rcnn_r50_1x
output_dir: output
run_mode: fluid
threshold: 0.5
use_gpu: True
------------------------------------------
-----------  Model Configuration -----------
Model Arch: RCNN
Use Paddle Executor: False
Transform Order: 
--transform op: Normalize
--transform op: Resize
--transform op: Permute
--------------------------------------------
W0324 17:55:07.368857  6811 analysis_predictor.cc:1058] Deprecated. Please use CreatePredictor instead.
Inference: 102.0808219909668 ms per batch image
[WARNNING] No object detected.
save result to: output/4.jpg
Inference: 101.22370719909668 ms per batch image
[WARNNING] No object detected.
save result to: output/5.jpg
Inference: 102.63204574584961 ms per batch image
save result to: output/sp6940546707212751477_NoBarcode1.jpg
Traceback (most recent call last):
  File "deploy/python/flask_infer.py", line 586, in <module>
    main()
  File "deploy/python/flask_infer.py", line 544, in main
    predict_image(detector)
  File "deploy/python/flask_infer.py", line 484, in predict_image
    results = detector.predict(img_file, FLAGS.threshold)
  File "deploy/python/flask_infer.py", line 190, in predict
    np_boxes = boxes_tensor.copy_to_cpu()
OSError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_to_cpu<float>(float*)
1   void paddle::memory::Copy<paddle::platform::CPUPlace, paddle::platform::CUDAPlace>(paddle::platform::CPUPlace, void*, paddle::platform::CUDAPlace, void const*, unsigned long, CUstream_st*)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:296)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AllocatorFacade::Release(paddle::platform::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
5   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   paddle::platform::RecordedCudaFree(void*, unsigned long, int)
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:411)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AllocatorFacade::Release(paddle::platform::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
5   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1616579713 (unix time) try "date -d @1616579713" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800001a9b) received by PID 6811 (TID 0x7fc5ce220700) from PID 6811 ***]

Aborted (core dumped)
```
请问这个问题如何修复？

**Comment by liuhuiCNN** [comment]
`np_boxes = boxes_tensor.copy_to_cpu()`
根据错误信息，报错是这行代码。上面会提示：No object detected.，这种情况下boxes_tensor是空的，因此会导致错误。建议在检测为空情况下，建议你避免 boxes_tensor.copy_to_cpu() 这个操作看看。

**Comment by hymanzhu1983** [comment]
加了判断，在检测boxex_tensor为空的情况下直接返回空的结果，继续检测下一张图片，依旧会出错：

```
Traceback (most recent call last):
  File "deploy/python/flask_infer.py", line 589, in <module>
    main()
  File "deploy/python/flask_infer.py", line 547, in main
    predict_image(detector)
  File "deploy/python/flask_infer.py", line 487, in predict_image
    results = detector.predict(img_file, FLAGS.threshold)
  File "deploy/python/flask_infer.py", line 162, in predict
    input_tensor.copy_from_cpu(inputs[input_names[i]])
OSError: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   void paddle::ZeroCopyTensor::copy_from_cpu<float>(float const*)
1   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CPUPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CPUPlace, void const*, unsigned long, CUstream_st*)
2   paddle::platform::GpuMemcpyAsync(void*, void const*, unsigned long, cudaMemcpyKind, CUstream_st*)
3   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
4   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:296)

terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AllocatorFacade::Release(paddle::platform::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
5   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   paddle::platform::RecordedCudaFree(void*, unsigned long, int)
7   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
8   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:411)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::AllocatorFacade::Release(paddle::platform::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::AlignedAllocation::~AlignedAllocation()
5   paddle::memory::allocation::CUDAAllocator::FreeImpl(paddle::memory::allocation::Allocation*)
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1616634720 (unix time) try "date -d @1616634720" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e800002e86) received by PID 11910 (TID 0x7f23d9a48700) from PID 11910 ***]

Aborted (core dumped)
```

**Comment by hymanzhu1983** [comment]
哪位大神可以帮忙看看怎么解决这个问题？

**Comment by hymanzhu1983** [comment]
请问有人帮忙看看这个问题吗？是不是跟paddle有关系？

**Comment by hymanzhu1983** [comment]
请问有没有人遇到同样的问题？

**Comment by liuhuiCNN** [comment]
你好，请问问题是否解决？

**Comment by hymanzhu1983** [comment]
没有解决的，建议你复现一下，我现在的walkaround是设置use_python_inference=1

**Comment by hymanzhu1983** [comment]
有人跟进吗？又过了10天了。还是你们复现不了？

**Comment by qingqing01** [comment]
@hymanzhu1983 抱歉，之前没有及时跟进，您如果是内部同学，我们拉个群解决下~

**Comment by hymanzhu1983** [comment]
不是内部的，我们尝试基于paddleDetection做产品，目前遇到的这个问题，有问题交流群吗？

**Comment by qingqing01** [comment]
@hymanzhu1983 已有同学定位到 https://github.com/PaddlePaddle/Paddle/blob/c809530eff4beb46329c5d6e1025fc50231c2a2b/paddle/fluid/framework/operator.cc#L1535 这里引起了，正在看怎么解决。

**Comment by hymanzhu1983** [comment]
修复了麻烦告之一下，谢谢

**Comment by hymanzhu1983** [comment]
请问这个bug修复了吗？

**Comment by aishangmaxiaoming** [comment]
我也遇到这个问题

**Comment by aishangmaxiaoming** [comment]
> @hymanzhu1983 已有同学定位到 https://github.com/PaddlePaddle/Paddle/blob/c809530eff4beb46329c5d6e1025fc50231c2a2b/paddle/fluid/framework/operator.cc#L1535 这里引起了，正在看怎么解决。

请问解决啦吗

**Comment by aishangmaxiaoming** [comment]
> @hymanzhu1983 抱歉，之前没有及时跟进，您如果是内部同学，我们拉个群解决下~

我是内部的同学，能拉个群解决下吗

**Comment by hymanzhu1983** [comment]
这个bug已经几个月了，是该解决了吧

**Comment by hymanzhu1983** [comment]
请问这个bug有什么进展吗？

**Comment by hymanzhu1983** [comment]
请问这个paddlepaddle的问题解决了吗？
