### ISSUE TITLE
使用mask_rcnn_r50_vd_fpn_ssld_2x_coco时，eval时报错

### ISSUE THREAD

**Issue by jerryandjune** [PaddlePaddle/PaddleDetection#3053]
在aistudio.baidu.com上训练实例分割模型，一边训练一边验证，就会出现这个错误，
PaddleDetection   release/2.0  版本
使用PaddleDetection-develop   也是一样的

env: CUDA_VISIBLE_DEVICES=0
/home/aistudio/PaddleDetection
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0518 10:12:16.619282   926 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.1
W0518 10:12:16.624701   926 device_context.cc:372] device: 0, cuDNN Version: 7.6.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
[05/18 10:12:19] ppdet.utils.download INFO: Downloading ResNet50_vd_ssld_v2_pretrained.pdparams from https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
100%|████████████████████████████████| 139208/139208 [00:02<00:00, 54898.54KB/s]
[05/18 10:12:23] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/aistudio/.cache/paddle/weights/ResNet50_vd_ssld_v2_pretrained.pdparams
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/target.py:235: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  return mask_util.decode(rle).astype(np.bool)
[05/18 10:12:23] ppdet.engine INFO: Epoch: [0] [  0/752] learning_rate: 0.001000 loss_mask: 1.175833 loss_rpn_cls: 0.691948 loss_rpn_reg: 0.105494 loss_bbox_cls: 1.984367 loss_bbox_reg: 0.032861 loss: 3.990502 eta: 1:11:16 batch_cost: 0.2369 data_cost: 0.0020 ips: 4.2205 images/s
[05/18 10:12:27] ppdet.engine INFO: Epoch: [0] [ 20/752] learning_rate: 0.001180 loss_mask: 0.678053 loss_rpn_cls: 0.670804 loss_rpn_reg: 0.048064 loss_bbox_cls: 0.360881 loss_bbox_reg: 0.029869 loss: 1.790904 eta: 0:58:24 batch_cost: 0.1923 data_cost: 0.0013 ips: 5.2010 images/s
[05/18 10:12:31] ppdet.engine INFO: Epoch: [0] [ 40/752] learning_rate: 0.001360 loss_mask: 0.610648 loss_rpn_cls: 0.505687 loss_rpn_reg: 0.058224 loss_bbox_cls: 0.252931 loss_bbox_reg: 0.089255 loss: 1.549267 eta: 0:58:35 batch_cost: 0.1961 data_cost: 0.0013 ips: 5.0989 images/s
[05/18 10:12:35] ppdet.engine INFO: Epoch: [0] [ 60/752] learning_rate: 0.001540 loss_mask: 0.554252 loss_rpn_cls: 0.212146 loss_rpn_reg: 0.049273 loss_bbox_cls: 0.337545 loss_bbox_reg: 0.245491 loss: 1.410815 eta: 0:59:13 batch_cost: 0.2023 data_cost: 0.0016 ips: 4.9444 images/s
[05/18 10:12:39] ppdet.engine INFO: Epoch: [0] [ 80/752] learning_rate: 0.001720 loss_mask: 0.560491 loss_rpn_cls: 0.146816 loss_rpn_reg: 0.061808 loss_bbox_cls: 0.335871 loss_bbox_reg: 0.298790 loss: 1.421197 eta: 0:59:34 batch_cost: 0.2032 data_cost: 0.0012 ips: 4.9209 images/s
[05/18 10:12:43] ppdet.engine INFO: Epoch: [0] [100/752] learning_rate: 0.001900 loss_mask: 0.507355 loss_rpn_cls: 0.119541 loss_rpn_reg: 0.043988 loss_bbox_cls: 0.334175 loss_bbox_reg: 0.308591 loss: 1.338458 eta: 0:59:48 batch_cost: 0.2040 data_cost: 0.0012 ips: 4.9027 images/s
[05/18 10:12:47] ppdet.engine INFO: Epoch: [0] [120/752] learning_rate: 0.002080 loss_mask: 0.501177 loss_rpn_cls: 0.115768 loss_rpn_reg: 0.052854 loss_bbox_cls: 0.365212 loss_bbox_reg: 0.337486 loss: 1.372319 eta: 0:59:47 batch_cost: 0.2010 data_cost: 0.0013 ips: 4.9747 images/s
[05/18 10:12:51] ppdet.engine INFO: Epoch: [0] [140/752] learning_rate: 0.002260 loss_mask: 0.442910 loss_rpn_cls: 0.114161 loss_rpn_reg: 0.052412 loss_bbox_cls: 0.419453 loss_bbox_reg: 0.353023 loss: 1.413565 eta: 0:59:59 batch_cost: 0.2063 data_cost: 0.0015 ips: 4.8476 images/s
[05/18 10:12:56] ppdet.engine INFO: Epoch: [0] [160/752] learning_rate: 0.002440 loss_mask: 0.422138 loss_rpn_cls: 0.096171 loss_rpn_reg: 0.049116 loss_bbox_cls: 0.356581 loss_bbox_reg: 0.345976 loss: 1.295549 eta: 1:00:14 batch_cost: 0.2095 data_cost: 0.0013 ips: 4.7730 images/s
[05/18 10:13:00] ppdet.engine INFO: Epoch: [0] [180/752] learning_rate: 0.002620 loss_mask: 0.417916 loss_rpn_cls: 0.094374 loss_rpn_reg: 0.047560 loss_bbox_cls: 0.376110 loss_bbox_reg: 0.376317 loss: 1.353478 eta: 1:00:20 batch_cost: 0.2074 data_cost: 0.0015 ips: 4.8227 images/s
[05/18 10:13:04] ppdet.engine INFO: Epoch: [0] [200/752] learning_rate: 0.002800 loss_mask: 0.382626 loss_rpn_cls: 0.090206 loss_rpn_reg: 0.049794 loss_bbox_cls: 0.321782 loss_bbox_reg: 0.339385 loss: 1.199532 eta: 1:00:25 batch_cost: 0.2075 data_cost: 0.0013 ips: 4.8182 images/s
[05/18 10:13:08] ppdet.engine INFO: Epoch: [0] [220/752] learning_rate: 0.002980 loss_mask: 0.401699 loss_rpn_cls: 0.086474 loss_rpn_reg: 0.043732 loss_bbox_cls: 0.366418 loss_bbox_reg: 0.386631 loss: 1.305320 eta: 1:00:22 batch_cost: 0.2037 data_cost: 0.0012 ips: 4.9085 images/s
[05/18 10:13:12] ppdet.engine INFO: Epoch: [0] [240/752] learning_rate: 0.003160 loss_mask: 0.397439 loss_rpn_cls: 0.087838 loss_rpn_reg: 0.054748 loss_bbox_cls: 0.396597 loss_bbox_reg: 0.435906 loss: 1.413173 eta: 1:00:32 batch_cost: 0.2128 data_cost: 0.0013 ips: 4.6988 images/s
[05/18 10:13:17] ppdet.engine INFO: Epoch: [0] [260/752] learning_rate: 0.003340 loss_mask: 0.371075 loss_rpn_cls: 0.074282 loss_rpn_reg: 0.039870 loss_bbox_cls: 0.369364 loss_bbox_reg: 0.371140 loss: 1.236417 eta: 1:00:42 batch_cost: 0.2140 data_cost: 0.0014 ips: 4.6733 images/s
[05/18 10:13:21] ppdet.engine INFO: Epoch: [0] [280/752] learning_rate: 0.003520 loss_mask: 0.454875 loss_rpn_cls: 0.082447 loss_rpn_reg: 0.052846 loss_bbox_cls: 0.381021 loss_bbox_reg: 0.386552 loss: 1.542152 eta: 1:00:47 batch_cost: 0.2123 data_cost: 0.0015 ips: 4.7096 images/s
[05/18 10:13:25] ppdet.engine INFO: Epoch: [0] [300/752] learning_rate: 0.003700 loss_mask: 0.521680 loss_rpn_cls: 0.097533 loss_rpn_reg: 0.061564 loss_bbox_cls: 0.396334 loss_bbox_reg: 0.385363 loss: 1.465978 eta: 1:00:45 batch_cost: 0.2074 data_cost: 0.0015 ips: 4.8214 images/s
[05/18 10:13:29] ppdet.engine INFO: Epoch: [0] [320/752] learning_rate: 0.003880 loss_mask: 0.455287 loss_rpn_cls: 0.075243 loss_rpn_reg: 0.046807 loss_bbox_cls: 0.352252 loss_bbox_reg: 0.370960 loss: 1.270976 eta: 1:00:49 batch_cost: 0.2122 data_cost: 0.0013 ips: 4.7121 images/s
[05/18 10:13:33] ppdet.engine INFO: Epoch: [0] [340/752] learning_rate: 0.004060 loss_mask: 0.425489 loss_rpn_cls: 0.073716 loss_rpn_reg: 0.045929 loss_bbox_cls: 0.321181 loss_bbox_reg: 0.368205 loss: 1.265468 eta: 1:00:42 batch_cost: 0.2035 data_cost: 0.0013 ips: 4.9139 images/s
[05/18 10:13:38] ppdet.engine INFO: Epoch: [0] [360/752] learning_rate: 0.004240 loss_mask: 0.385620 loss_rpn_cls: 0.070022 loss_rpn_reg: 0.042729 loss_bbox_cls: 0.321375 loss_bbox_reg: 0.353763 loss: 1.235781 eta: 1:00:48 batch_cost: 0.2154 data_cost: 0.0014 ips: 4.6432 images/s
[05/18 10:13:42] ppdet.engine INFO: Epoch: [0] [380/752] learning_rate: 0.004420 loss_mask: 0.312166 loss_rpn_cls: 0.056243 loss_rpn_reg: 0.048036 loss_bbox_cls: 0.264553 loss_bbox_reg: 0.304013 loss: 1.020425 eta: 1:00:44 batch_cost: 0.2073 data_cost: 0.0013 ips: 4.8244 images/s
[05/18 10:13:46] ppdet.engine INFO: Epoch: [0] [400/752] learning_rate: 0.004600 loss_mask: 0.340127 loss_rpn_cls: 0.050384 loss_rpn_reg: 0.042839 loss_bbox_cls: 0.276612 loss_bbox_reg: 0.314221 loss: 1.127935 eta: 1:00:42 batch_cost: 0.2081 data_cost: 0.0015 ips: 4.8059 images/s
[05/18 10:13:50] ppdet.engine INFO: Epoch: [0] [420/752] learning_rate: 0.004780 loss_mask: 0.312006 loss_rpn_cls: 0.062560 loss_rpn_reg: 0.051231 loss_bbox_cls: 0.338978 loss_bbox_reg: 0.367567 loss: 1.170205 eta: 1:00:41 batch_cost: 0.2099 data_cost: 0.0014 ips: 4.7641 images/s
[05/18 10:13:55] ppdet.engine INFO: Epoch: [0] [440/752] learning_rate: 0.004960 loss_mask: 0.329643 loss_rpn_cls: 0.056023 loss_rpn_reg: 0.041953 loss_bbox_cls: 0.315621 loss_bbox_reg: 0.370182 loss: 1.129866 eta: 1:00:35 batch_cost: 0.2052 data_cost: 0.0014 ips: 4.8742 images/s
[05/18 10:13:59] ppdet.engine INFO: Epoch: [0] [460/752] learning_rate: 0.005140 loss_mask: 0.366782 loss_rpn_cls: 0.039472 loss_rpn_reg: 0.039703 loss_bbox_cls: 0.325514 loss_bbox_reg: 0.418611 loss: 1.246041 eta: 1:00:39 batch_cost: 0.2165 data_cost: 0.0014 ips: 4.6186 images/s
[05/18 10:14:03] ppdet.engine INFO: Epoch: [0] [480/752] learning_rate: 0.005320 loss_mask: 0.319073 loss_rpn_cls: 0.035175 loss_rpn_reg: 0.040303 loss_bbox_cls: 0.270629 loss_bbox_reg: 0.366159 loss: 1.033410 eta: 1:00:38 batch_cost: 0.2107 data_cost: 0.0012 ips: 4.7458 images/s
[05/18 10:14:08] ppdet.engine INFO: Epoch: [0] [500/752] learning_rate: 0.005500 loss_mask: 0.265720 loss_rpn_cls: 0.028858 loss_rpn_reg: 0.042702 loss_bbox_cls: 0.239805 loss_bbox_reg: 0.362709 loss: 0.979312 eta: 1:00:37 batch_cost: 0.2118 data_cost: 0.0013 ips: 4.7212 images/s
[05/18 10:14:12] ppdet.engine INFO: Epoch: [0] [520/752] learning_rate: 0.005680 loss_mask: 0.262734 loss_rpn_cls: 0.035198 loss_rpn_reg: 0.042631 loss_bbox_cls: 0.233480 loss_bbox_reg: 0.344499 loss: 0.931892 eta: 1:00:50 batch_cost: 0.2338 data_cost: 0.0014 ips: 4.2771 images/s
[05/18 10:14:17] ppdet.engine INFO: Epoch: [0] [540/752] learning_rate: 0.005860 loss_mask: 0.292046 loss_rpn_cls: 0.027943 loss_rpn_reg: 0.047965 loss_bbox_cls: 0.297333 loss_bbox_reg: 0.457230 loss: 1.199237 eta: 1:00:52 batch_cost: 0.2169 data_cost: 0.0014 ips: 4.6109 images/s
[05/18 10:14:21] ppdet.engine INFO: Epoch: [0] [560/752] learning_rate: 0.006040 loss_mask: 0.279336 loss_rpn_cls: 0.031255 loss_rpn_reg: 0.043601 loss_bbox_cls: 0.274191 loss_bbox_reg: 0.390399 loss: 1.025233 eta: 1:00:53 batch_cost: 0.2167 data_cost: 0.0013 ips: 4.6150 images/s
[05/18 10:14:25] ppdet.engine INFO: Epoch: [0] [580/752] learning_rate: 0.006220 loss_mask: 0.248155 loss_rpn_cls: 0.028584 loss_rpn_reg: 0.051620 loss_bbox_cls: 0.290709 loss_bbox_reg: 0.395196 loss: 1.041463 eta: 1:00:48 batch_cost: 0.2072 data_cost: 0.0014 ips: 4.8262 images/s
[05/18 10:14:29] ppdet.engine INFO: Epoch: [0] [600/752] learning_rate: 0.006400 loss_mask: 0.235673 loss_rpn_cls: 0.029767 loss_rpn_reg: 0.048746 loss_bbox_cls: 0.248176 loss_bbox_reg: 0.373360 loss: 0.952668 eta: 1:00:44 batch_cost: 0.2105 data_cost: 0.0018 ips: 4.7516 images/s
[05/18 10:14:34] ppdet.engine INFO: Epoch: [0] [620/752] learning_rate: 0.006580 loss_mask: 0.237986 loss_rpn_cls: 0.025156 loss_rpn_reg: 0.039185 loss_bbox_cls: 0.218605 loss_bbox_reg: 0.336960 loss: 0.879146 eta: 1:00:43 batch_cost: 0.2134 data_cost: 0.0019 ips: 4.6869 images/s
[05/18 10:14:38] ppdet.engine INFO: Epoch: [0] [640/752] learning_rate: 0.006760 loss_mask: 0.245194 loss_rpn_cls: 0.021596 loss_rpn_reg: 0.050676 loss_bbox_cls: 0.281108 loss_bbox_reg: 0.483732 loss: 1.080559 eta: 1:00:44 batch_cost: 0.2184 data_cost: 0.0019 ips: 4.5783 images/s
[05/18 10:14:43] ppdet.engine INFO: Epoch: [0] [660/752] learning_rate: 0.006940 loss_mask: 0.265808 loss_rpn_cls: 0.023808 loss_rpn_reg: 0.040615 loss_bbox_cls: 0.224546 loss_bbox_reg: 0.372139 loss: 0.898500 eta: 1:00:44 batch_cost: 0.2189 data_cost: 0.0022 ips: 4.5683 images/s
[05/18 10:14:47] ppdet.engine INFO: Epoch: [0] [680/752] learning_rate: 0.007120 loss_mask: 0.219472 loss_rpn_cls: 0.020118 loss_rpn_reg: 0.050209 loss_bbox_cls: 0.213213 loss_bbox_reg: 0.349246 loss: 0.851861 eta: 1:00:43 batch_cost: 0.2155 data_cost: 0.0019 ips: 4.6406 images/s
[05/18 10:14:51] ppdet.engine INFO: Epoch: [0] [700/752] learning_rate: 0.007300 loss_mask: 0.230046 loss_rpn_cls: 0.025600 loss_rpn_reg: 0.045166 loss_bbox_cls: 0.221463 loss_bbox_reg: 0.412765 loss: 0.966488 eta: 1:00:44 batch_cost: 0.2201 data_cost: 0.0013 ips: 4.5441 images/s
[05/18 10:14:56] ppdet.engine INFO: Epoch: [0] [720/752] learning_rate: 0.007480 loss_mask: 0.189543 loss_rpn_cls: 0.011251 loss_rpn_reg: 0.042119 loss_bbox_cls: 0.194555 loss_bbox_reg: 0.318709 loss: 0.765211 eta: 1:00:46 batch_cost: 0.2230 data_cost: 0.0013 ips: 4.4838 images/s
[05/18 10:15:00] ppdet.engine INFO: Epoch: [0] [740/752] learning_rate: 0.007660 loss_mask: 0.206307 loss_rpn_cls: 0.019097 loss_rpn_reg: 0.037947 loss_bbox_cls: 0.225572 loss_bbox_reg: 0.334677 loss: 0.859600 eta: 1:00:44 batch_cost: 0.2149 data_cost: 0.0013 ips: 4.6532 images/s
[05/18 10:15:07] ppdet.utils.checkpoint INFO: Save checkpoint: output/mask_rcnn_r50_vd_fpn_ssld_2x_coco
loading annotations into memory...
Done (t=0.13s)
creating index...
index created!
[05/18 10:15:08] ppdet.engine INFO: Eval iter: 0
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 317, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 333, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 140, in forward
    batch_size)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 167, in _gen_proposal
    im_shape=im_shape[i:i + 1])
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/proposal_generator.py", line 80, in __call__
    return_rois_num=True)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/ops.py", line 1499, in generate_proposals
    scores, bbox_deltas, im_shape, anchors, variances, *attrs)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:296)
  [operator < generate_proposals_v2 > error]

**Comment by wangxinxin08** [comment]
你好，问题正在定位中

**Comment by jerrywgz** [comment]
可以更新下develop版本，目前已经尝试修复训练过程中可能出现的空box情况，导致出现cuda error

**Comment by jerryandjune** [comment]
已经更新到最新的develop版本，训练过程中，还是在--eval 时出现cuda error，报错信息如下：
不添加--eval的话，训练时过程没有报错


loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[05/20 15:56:51] ppdet.engine INFO: Eval iter: 0
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 143, in forward
    batch_size)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 170, in _gen_proposal
    im_shape=im_shape[i:i + 1])
  File "/home/aistudio/PaddleDetection/ppdet/modeling/proposal_generator/proposal_generator.py", line 80, in __call__
    return_rois_num=True)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/ops.py", line 1517, in generate_proposals
    scores, bbox_deltas, im_shape, anchors, variances, *attrs)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]

**Comment by jerryandjune** [comment]
!python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml \
                        --use_vdl=true \
                        --vdl_log_dir=vdl_dir/scalar \
                        --eval \               
                        # -r output/mask_rcnn_r50_vd_fpn_ssld_2x_coco/75.pdparams
使用以上命令训练时，--eval 不注释，就会出现

**Comment by jerrywgz** [comment]
能否提供少量测试数据呢，我本地验证下，可以发我邮箱jerrywgz@126.com

**Comment by xialei2821212670** [comment]
mask_rcnn_x101_vd_64x4d_fpn_2x_coco也是这个问题，目前我直接注释eval,不知道如何选取bestmodel

**Comment by jerrywgz** [comment]
已经定位到问题，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/post_process.py#L165 可以现在这一行的align_corner设置为True.align_corner为False是会有越界的情况，我们会在下版本的paddle中修复

**Comment by xialei2821212670** [comment]
> 已经定位到问题，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/post_process.py#L165可以现在这一行的align_corner设置为True.align_corner为False是会有越界的情况，我们会在下版本的paddle中修复
好的，之前训练的如何评估啊

**Comment by jerryandjune** [comment]
> 已经定位到问题，https://github.com/PaddlePaddle/PaddleDetection/blob/develop/ppdet/modeling/post_process.py#L165 可以现在这一行的align_corner设置为True.align_corner为False是会有越界的情况，我们会在下版本的paddle中修复

手动修改为True解决了问题，谢谢！！

**Comment by Meryl-Fang** [comment]
@jerrywgz 我们训练时eval也遇到了这个问题 手动改了align_corner=True也还是有Cuda700的错误, 请问大佬有什么见解吗？

cuda=10.2
cudnn=7.6
paddledet=2.0.1

**Comment by Meryl-Fang** [comment]
> @jerrywgz 我们训练时eval也遇到了这个问题 手动改了align_corner=True也还是有Cuda700的错误, 请问大佬有什么见解吗？
> 
> cuda=10.2
> cudnn=7.6
> paddledet=2.0.1

破案了，原来是没有设置PYTHONPATH所以一直在用site-package里的包
