### ISSUE TITLE
Out of memory erroe on GPU0

### ISSUE THREAD

**Issue by xuanyuanbao** [PaddlePaddle/PaddleDetection#3100]
Out of memory error on GPU 0. Cannot allocate 18.062744MB memory on GPU 0, available memory is only 17.537501MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at D:\v2.0.1\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)
. (at D:\v2.0.1\paddle\paddle\fluid\imperative\tracer.cc:172)

**Comment by jerrywgz** [comment]
You could try ```export FLAGS_allocator_strategy=auto_growth ```
And you need to check whether the GPU is able to carry your model.

**Comment by xuanyuanbao** [comment]
谢谢，我已经改了batch_size的大小了

**Comment by jerrywgz** [comment]
使用的是哪个模型呢，我这边测试下

**Comment by xuanyuanbao** [comment]
在  README_cn.md    文件中的
                 快速开始.md中的一段代码
python tools/train.py -c configs/yolov3/yolov3_mobilenet_v1_roadsign.yml --eval -o use_gpu=true

batch_size默认是8，我将其改成了4就可以啦

**Comment by DongLZY** [comment]
你好，我用的PPyolov2训练出现了同样情况，我看显存应该是够的呀！batchsize改成1了都不行

**Comment by jerrywgz** [comment]
export FLAGS_allocator_strategy=auto_growth
尝试下这个FLAG呢

**Comment by kaixin-bai** [comment]
我遇到同样的情况，更改了CUDNN的版本，改小了batch_size的大小，然后也用了`export FLAGS_allocator_strategy=auto_growth`后可以正常训练了
