### ISSUE TITLE
利用mask_rcnn_r50_vd_fpn_ssld_2x_coco训练时报错

### ISSUE THREAD

**Issue by shen-wenxin** [PaddlePaddle/PaddleDetection#3311]
环境：cuda 10.1 / cudnn 7.6.4

利用以下命令进行训练
python tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_2x_coco.yml --eval

然后训练的时候没问题，但是eval的时候报错如下：
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
[06/07 23:20:33] ppdet.engine INFO: Eval iter: 0
Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/engine/trainer.py", line 350, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/engine/trainer.py", line 366, in _eval_with_loader
    outs = self.model(data)
  File "/home/airs/.conda/envs/paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "/home/airs/.conda/envs/paddlex/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 143, in forward
    batch_size)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 178, in _gen_proposal
    im_shape=im_shape[i:i + 1])
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/proposal_generator/proposal_generator.py", line 80, in __call__
    return_rois_num=True)
  File "/home/airs/swx_ws/swx/competition/PaddleDetection/ppdet/modeling/ops.py", line 1517, in generate_proposals
    scores, bbox_deltas, im_shape, anchors, variances, *attrs)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]

**Comment by lyuwenyu** [comment]
也提供一下paddle和ppdet的版本信息吧

**Comment by shen-wenxin** [comment]
您好
paddle:2.1.0
ppdet的版本号该怎么查看呢

谢谢

**Comment by lyuwenyu** [comment]
> 您好
> paddle:2.1.0
> ppdet的版本号该怎么查看呢
> 
> 谢谢

看一下分支信息  `git branch`

**Comment by shen-wenxin** [comment]
> > 您好
> > paddle:2.1.0
> > ppdet的版本号该怎么查看呢
> > 谢谢
> 
> 看一下分支信息 `git branch`

您好，paddleDetection的分支是release/2.1
然后是根据快速安装教程配的环境
其中paddledet==2.1.0

谢谢

**Comment by lyuwenyu** [comment]
我使用下边的配置 没有复现你这个错误，建议你单独eval试一下 
- driver 418.67
- cuda 10.1
- cuDNN 7.6
- paddle 2.1 
- ppdet branch release/2.1

**Comment by ResonLee** [comment]
@shen-wenxin @lyuwenyu 问题解决的吗？出现了同样的问题，训练完第一轮后在第一次评估的时候报错，我以为是图片尺寸太大，改为target_size[600,800]还是出错，paddle2.0.1 paddledetection2.0.0

**Comment by shen-wenxin** [comment]
> @shen-wenxin @lyuwenyu 问题解决的吗？出现了同样的问题，训练完第一轮后在第一次评估的时候报错，我以为是图片尺寸太大，改为target_size[600,800]还是出错，paddle2.0.1 paddledetection2.0.0

没解决，我回退到2.0版本了，然后我用2.0版本已经做完项目了。
你可以回退到2.0版本试试，感觉还不错。

**Comment by shen-wenxin** [comment]
> @shen-wenxin @lyuwenyu 问题解决的吗？出现了同样的问题，训练完第一轮后在第一次评估的时候报错，我以为是图片尺寸太大，改为target_size[600,800]还是出错，paddle2.0.1 paddledetection2.0.0

噢你原来就是2.0版本……那没事了……

**Comment by ResonLee** [comment]
@lyuwenyu OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\v2.0.2\paddle\paddle\fluid\platform\gpu_info.cc:296)
  [operator < generate_proposals_v2 > error]

**Comment by lyuwenyu** [comment]
- 请使用paddle develop 或者 等paddle2.1.1发版

**Comment by ResonLee** [comment]
@lyuwenyu ，使用paddle develop 还是出现同样的问题，到底该怎么样解决啊？崩溃！
`OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]`

**Comment by ResonLee** [comment]
@lyuwenyu 完整报错如下
`Traceback (most recent call last):
  File "tools/train.py", line 140, in <module>
    main()
  File "tools/train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 358, in train
    self._eval_with_loader(self._eval_loader)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\engine\trainer.py", line 374, in _eval_with_loader
    outs = self.model(data)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\meta_arch.py", line 29, in forward
    out = self.get_pred()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\architectures\mask_rcnn.py", line 103, in _forward
    rois, rois_num, _ = self.rpn_head(body_feats, self.inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 136, in forward
    rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\rpn_head.py", line 168, in _gen_proposal
    rpn_rois, rpn_rois_prob, rpn_rois_num, post_nms_top_n = prop_gen(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\proposal_generator\proposal_generator.py", line 69, in __call__
    rpn_rois, rpn_rois_prob, rpn_rois_num = ops.generate_proposals(
  File "D:\Anaconda\anaconda\envs\Paddle\lib\site-packages\paddledet-2.1.0-py3.8.egg\ppdet\modeling\ops.py", line 1516, in generate_proposals
    rpn_rois, rpn_roi_probs, rpn_rois_num = core.ops.generate_proposals_v2(
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:382)
  [operator < generate_proposals_v2 > error]`
