### ISSUE TITLE
paddle inference c++ api连续预测报错

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3754]
你好，我采用paddle inference的c++ api进行多张图像连续预测时，如果中间有一张喂入的图像没有目标被检测到之后，shared_ptr<paddle_infer::Predictor> predictor就会产生错误，接下来预测任何图片都会在运行到predictor.Run()产生错误，该错误有时能被try-catch捕获有时不能。接着再预测就会报如下cuda访问错误：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at C:\home\workspace\Paddle_release\paddle\fluid\platform\gpu_info.cc:553)
```

我尝试了predictor的如下指令，没有效果
```
predictor_->ClearIntermediateTensor();
predictor_->TryShrinkMemory();
```
请问可能什么原因导致？如何改进？

我的软件版本：
paddle detection2.1训练模型导出部署模型
paddle inference2.1+trt7.0+cuda10.2

**Comment by ximitiejiang** [comment]
如果被预测的所有图片都有样本被检测，则不会产生上面的问题。
是不是因为没有检测到所以predictor内部部分驻留变量对后续检测产生了影响，才导致predictor.Run()无法运行？

**Comment by jerrywgz** [comment]
可以更新下Paddle版本，连续预测报错的问题在新版本已经解决了

**Comment by ximitiejiang** [comment]
更新到paddle inference2.1.1搞定，thanks
