### ISSUE TITLE
求助！！！S2ANet运行预测时报错：OSError: (External)  Cublas error, `CUBLAS_STATUS_EXECUTION_FAILED`. The GPU program failed to execute. This is often caused by a launch failure of the kernel on the GPU, which can be caused by multiple reasons.  (at /paddle/paddle/fluid/operators/math/blas_impl.cu.h:35)

### ISSUE THREAD

**Issue by jacksonqin037** [PaddlePaddle/PaddleDetection#4043]
显卡：RTX3000
cuda:10.1
cudnn:7.6.3
python:3.6
更新gcc版本也没解决
谢谢大家

**Comment by jerrywgz** [comment]
如果是RTX30系列显卡，建议使用cuda11.0以上的版本，并安装配套的paddle版本

**Comment by jacksonqin037** [comment]
> 
> 
> 如果是RTX30系列显卡，建议使用cuda11.0以上的版本，并安装配套的paddle版本

十分感谢，问题已经解决
