### ISSUE TITLE
实例分割mask-rcnn，裁剪训练和评估都是正常的，推理的时候就报错了

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/PaddleDetection#4071]
版本：release/2.2
报错如下：
Traceback (most recent call last):
  File "tools/infer.py", line 161, in <module>
    main()
  File "tools/infer.py", line 157, in main
    run(FLAGS, cfg)
  File "tools/infer.py", line 131, in run
    trainer.predict(
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/engine/trainer.py", line 470, in predict
    outs = self.model(data)
  File "/home/su/PycharmProjects/PaddleDetection/venv/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/modeling/architectures/meta_arch.py", line 28, in forward
    out = self.get_pred()
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/modeling/architectures/mask_rcnn.py", line 118, in _forward
    mask_pred = self.mask_post_process(mask_out[:, 0, :, :], bbox_pred,
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/modeling/post_process.py", line 196, in __call__
    pred_mask = self.paste_mask(mask_out[i], bboxes[i:i + 1, 2:], im_h,
  File "/home/su/PycharmProjects/PaddleDetection/2.1/ppdet/modeling/post_process.py", line 154, in paste_mask
    img_y = paddle.arange(0, im_h, dtype='float32') + 0.5
  File "/home/su/PycharmProjects/PaddleDetection/venv/lib/python3.8/site-packages/paddle/tensor/creation.py", line 533, in arange
    return paddle.fluid.layers.range(start, end, step, dtype, name)
  File "/home/su/PycharmProjects/PaddleDetection/venv/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 1420, in range
    return core.ops.range(start, end, step)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/9.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:382)
  [operator < range > error]

**Comment by ghostxsl** [comment]
这里看到您使用的是2.1版本，建议更新到最新版本试一下～

**Comment by yangy996** [comment]
> 这里看到您使用的是2.1版本，建议更新到最新版本试一下～

是最新的2.2版本，我切换了版本，文件夹名字还没换

**Comment by ghostxsl** [comment]
请提供能够复现错误的详细环境及运行命令，以便能够帮助排查问题。

我在CUDA10.1 + paddle 2.1.2 + paddledetection 2.2版本下运行命令：python3.7 tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_1x_coco.yml --infer_img=demo/road554.png -o weights=mask_rcnn_r50_1x_coco.pdparams 是可以跑通的，截图如下：
![image](https://user-images.githubusercontent.com/23647349/131280961-79fb73b2-4972-439d-a61f-410f40ba910c.png)

**Comment by yangy996** [comment]
> 请提供能够复现错误的详细环境及运行命令，以便能够帮助排查问题。
> 
> 我在CUDA10.1 + paddle 2.1.2 + paddledetection 2.2版本下运行命令：python3.7 tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_1x_coco.yml --infer_img=demo/road554.png -o weights=mask_rcnn_r50_1x_coco.pdparams 是可以跑通的，截图如下：
> ![image](https://user-images.githubusercontent.com/23647349/131280961-79fb73b2-4972-439d-a61f-410f40ba910c.png)

我用这个命令先裁剪模型，然后使用裁剪后的模型进行预测，命令如下：
python -m paddle.distributed.launch --gpus 1,2,3,4 tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x.yml --slim_config configs/slim/prune/faster_rcnn_r50_fpn_prune_fpgm.yml  --use_vdl=true --vdl_log_dir=vdl_dir/mask_rcnn/ --eval


python tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x.yml --slim_config configs/slim/prune/faster_rcnn_r50_fpn_prune_fpgm.yml -o weights=output/faster_rcnn_r50_fpn_prune_fpgm/best_model --output_dir=infer_output/ --infer_dir=../train_data/small/cocome/test/

**Comment by ghostxsl** [comment]
亲，首先，我没找到configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x.yml文件，我用了configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x_coco.yml，其他跟你一样没变。

为了快速验证，我裁剪训练只跑了一个epoch后保存模型，然后进行预测，没有报错，可以正常运行：python3.7 tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x_coco.yml --slim_config configs/slim/prune/faster_rcnn_r50_fpn_prune_fpgm.yml -o weights=output/faster_rcnn_r50_fpn_prune_fpgm/0.pdparams --infer_dir=demo/
![image](https://user-images.githubusercontent.com/23647349/131295173-8c586f2d-ce3a-4de4-a83c-9b28ab6ff54d.png)

你可以检查一下运行环境是否有问题～

**Comment by yangy996** [comment]
> 亲，首先，我没找到configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x.yml文件，我用了configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x_coco.yml，其他跟你一样没变。
> 
> 为了快速验证，我裁剪训练只跑了一个epoch后保存模型，然后进行预测，没有报错，可以正常运行：python3.7 tools/infer.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_ssld_1x_coco.yml --slim_config configs/slim/prune/faster_rcnn_r50_fpn_prune_fpgm.yml -o weights=output/faster_rcnn_r50_fpn_prune_fpgm/0.pdparams --infer_dir=demo/
> ![image](https://user-images.githubusercontent.com/23647349/131295173-8c586f2d-ce3a-4de4-a83c-9b28ab6ff54d.png)
> 
> 你可以检查一下运行环境是否有问题～

。。。找到问题了，没有执行export CUDA_VISIBLE_DEVICES=0
