### ISSUE TITLE
Failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure

### ISSUE THREAD

**Issue by usuixingyili** [PaddlePaddle/PaddleDetection#4118]
mask rcnn 在以下两种软硬件环境下训练均报错，yolov3和ppyolo均可以训
NVIDIA GeForce GTX1080Ti 显存11G CUDA10.2 paddlepaddle 2.1.2 ppdet 2.2
NVIDIA GeForce RTX3090 显存24G CUDA11.2 paddlepaddle 2.1.2 ppdet 2.2

```
(ppdet) I:\PaddleDetection>python tools\train.py -c configs\mask_rcnn\mask_rcnn_r50_fpn_1x_coco.yml --eval
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
W0906 10:06:42.370529 11736 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runt
ime API Version: 10.2
W0906 10:06:42.378882 11736 device_context.cc:422] device: 0, cuDNN Version: 7.6.
[09/06 10:06:44] ppdet.utils.checkpoint INFO: Finish loading model weights: C:\Users\iplant/.cache/paddle/weights\ResNet50_cos_pretrai
ned.pdparams
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
Error: C:/home/workspace/Paddle_release2/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0
&& labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.
Error: C:/home/workspace/Paddle_release2/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0
&& labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.
Error: C:/home/workspace/Paddle_release2/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0
&& labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.
Error: C:/home/workspace/Paddle_release2/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0
&& labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.
Error: C:/home/workspace/Paddle_release2/paddle/fluid/operators/softmax_with_cross_entropy_op.cu:536 Assertion `labels_[idx_lbl] >= 0
&& labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.
Traceback (most recent call last):
  File "tools\train.py", line 140, in <module>
    main()
  File "tools\train.py", line 136, in main
    run(FLAGS, cfg)
  File "tools\train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\engine\trainer.py", line 307, in train
    outputs = model(data)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\meta_arch.py", line 27, in forward
    out = self.get_loss()
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 123, in get_loss
    bbox_loss, mask_loss, rpn_loss = self._forward()
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\architectures\mask_rcnn.py", line 95, in _forward
    self.inputs)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\dygraph\layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\heads\bbox_head.py", line 255, in forward
    self.bbox_weight)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\ppdet\modeling\heads\bbox_head.py", line 294, in get_loss
    self.num_classes)).flatten()
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\layers\nn.py", line 12179, in logical_and
    op_name="logical_and", x=x, y=y, name=name, out=out, binary_op=True)
  File "E:\opensources\Anaconda3\envs\ppdet\lib\site-packages\paddle\fluid\layers\nn.py", line 12118, in _logical_op
    return op(x, y)
SystemError: (Fatal) Operator logical_and raises an class thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure. (at C:\home\workspace\Paddle_release2\paddle\fl
uid\imperative\tracer.cc:192)
```

**Comment by qingqing01** [comment]
> labels_[idx_lbl] >= 0  && labels_[idx_lbl] < d_ || labels_[idx_lbl] == ignore_idx_` failed. The value of label[0] expected >= 0 and < 0, or == 5,but got 0. P
lease check input value.

看起来您指定的class number不太对。 导致计算softmax_with_cross_entropy_op时对label的判断出错。

**Comment by usuixingyili** [comment]
谢谢，该问题已解决。

**Comment by houxiaonan** [comment]
请问怎么解决的？

**Comment by usuixingyili** [comment]
> 请问怎么解决的？

num_classes不对，到annotation.json中查看类别数
