### ISSUE TITLE
SystemError: (Fatal) Operator logical_and raises an thrust::system::system_error exception.

### ISSUE THREAD

**Issue by MorningWind** [PaddlePaddle/PaddleDetection#4142]
when I use AI studio, I used the cascade_rcnn_r50_vd_fpn_ssld_2x_coco.yml of paddledetection, but I met such a problem when I train:

```
**SystemError: (Fatal) Operator logical_and raises an thrust::system::system_error exception.
The exception content is
:transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered. (at /paddle/paddle/fluid/imperative/tracer.cc:192)**

```

What happened and how can I solve it ?

**Comment by heavengate** [comment]
你好，你用的Paddle和PaddleDetection版本是啥呢

**Comment by MorningWind** [comment]
> 你好，你用的Paddle和PaddleDetection版本是啥呢

我是在ai studio上跑的  paddlepaddle是最新的2.1.2  paddledetection 是最新的release2.2版本 

我之前用同样的配置跑数据集没有报这个错  现在换了个更大的数据集跑的时候报这个错
我觉得可能是数据集哪里出了问题

**Comment by qingqing01** [comment]
是有更多的错误信息？ 具体到Python代码的行数。

**Comment by MorningWind** [comment]
> 是有更多的错误信息？ 具体到Python代码的行数。

你好，报错信息如下：（这个错跟我提问报的有点不同，反正就是这两种报错法轮流出现，这次是我刚跑的报错信息）

```
Traceback (most recent call last):
  File "tools/train.py", line 138, in <module>
    main()
  File "tools/train.py", line 134, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 109, in run
    trainer.train(FLAGS.eval)
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/engine/trainer.py", line 358, in train
    outputs = model(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/architectures/meta_arch.py", line 26, in forward
    out = self.get_loss()
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/architectures/cascade_rcnn.py", line 125, in get_loss
    rpn_loss, bbox_loss, mask_loss = self._forward()
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/architectures/cascade_rcnn.py", line 94, in _forward
    self.inputs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/heads/cascade_head.py", line 209, in forward
    rois, rois_num, targets = self.bbox_assigner(rois, rois_num, inputs)
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/proposal_generator/target_layer.py", line 152, in __call__
    self.cascade_iou[stage])
  File "/home/aistudio/PaddleDetection_all_dataset/ppdet/modeling/proposal_generator/target.py", line 194, in generate_proposal_target
    gt_class = paddle.squeeze(gt_classes[i], axis=-1)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/manipulation.py", line 613, in squeeze
    return layers.squeeze(x, axis, name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/nn.py", line 6266, in squeeze
    out, _ = core.ops.squeeze2(input, 'axes', axes)
OSError: (External)  Cuda error(700), an illegal memory access was encountered.
  [Advise: Please search for the error code(700) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at /paddle/paddle/fluid/platform/gpu_info.cc:394)
  [operator < squeeze2 > error]
```

请问是什么问题呢？

**Comment by xiaojifu** [comment]
请问解决了吗？我也遇到了同样的问题

**Comment by MorningWind** [comment]
> 请问解决了吗？我也遇到了同样的问题

解决了，我当时是因为做的数据集里面，有些xml文件生成了但是里面没框，把这些xml修改或者去掉就好了，不知道你是不是这个问题。

**Comment by xiaojifu** [comment]
> > 请问解决了吗？我也遇到了同样的问题
> 
> 解决了，我当时是因为做的数据集里面，有些xml文件生成了但是里面没框，把这些xml修改或者去掉就好了，不知道你是不是这个问题。

我训练没问题但是在评估的时候会报这个错误

**Comment by gloria111** [comment]
我也遇到了同样的问题,用的是COCO数据集

**Comment by gloria111** [comment]
(Fatal) Operator less_than raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument.
