### ISSUE TITLE
[Other General Issues] Could not load library libcudnn_cnn_train.so.8. Error: /home/jim/miniconda3/envs/pp21/bin/../lib/libcudnn_ops_train.so.8

### ISSUE THREAD

**Issue by yuanjim** [PaddlePaddle/PaddleDetection#4298]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## Checklist:

1. 查找历史相关issue寻求解答/I have searched related issues but cannot get the expected help.
2. 翻阅[FAQ](https://paddledetection.readthedocs.io/FAQ.html) /I have read the [FAQ documentation](https://paddledetection.readthedocs.io/FAQ.html) but cannot get the expected help.

## 描述问题/Describe the bug
同一个环境，paddleseg可以正常训练，但是paddledetection却出现问题如下：
Could not load library libcudnn_cnn_train.so.8. Error: /home/jim/miniconda3/envs/pp21/bin/../lib/libcudnn_ops_train.so.8 
百思不得其解，已试过cp libcudnn* 等方法，试了半天解决不了，请百度大佬助力。

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?
```none
GPU单卡：
export CUDA_VISIBLE_DEVICES=0 
python tools/train.py -c configs/ppyolo/ppyolo_mbv3_large_coco_infrared.yml
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
更改过datasets/coco_detection.yml，但常规操作理应这不影响模型训练。
```none
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instances_train.json
    dataset_dir: coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instances_val.json
    dataset_dir: coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val.json
```

3. 您使用的数据集是？/What dataset did you use?
自己用labelme标注的数据集，转成coco格式。

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
```none
(pp21) jim@jim-HP:~/Desktop/0024_infrared_image_detection$ python tools/train.py -c configs/ppyolo/ppyolo_mbv3_large_coco_infrared.yml

/home/jim/miniconda3/envs/pp21/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Warning: import ppdet from source directory without installing, run 'python setup.py install' to install ppdet firstly
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W1012 20:47:14.703162 13165 device_context.cc:404] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.4, Runtime API Version: 11.2
W1012 20:47:14.705763 13165 device_context.cc:422] device: 0, cuDNN Version: 8.2.
[10/12 20:47:15] ppdet.utils.checkpoint INFO: Finish loading model weights: pretrained/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
/home/jim/miniconda3/envs/pp21/lib/python3.8/site-packages/paddle/tensor/creation.py:125: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
Could not load library libcudnn_cnn_train.so.8. Error: /home/jim/miniconda3/envs/pp21/bin/../lib/libcudnn_ops_train.so.8: symbol _Z22cudnnGenericOpTensorNdILi3EE13cudnnStatus_tP12cudnnContext16cudnnGenericOp_t21cudnnNanPropagation_tPKdPKvPK17cudnnTensorStructS8_S8_SB_S8_S8_SB_Pv version libcudnn_ops_infer.so.8 not defined in file libcudnn_ops_infer.so.8 with link time reference
Please make sure libcudnn_cnn_train.so.8 is in your library path!


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framework::AttributeMap const&)
2   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CUDAPlace, false, 0ul, paddle::operators::CUDNNConvGradOpKernel<float>, paddle::operators::CUDNNConvGradOpKernel<double>, paddle::operators::CUDNNConvGradOpKernel<paddle::platform::float16> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
3   paddle::operators::CUDNNConvGradOpKernel<float>::Compute(paddle::framework::ExecutionContext const&) const
4   cudnnConvolutionBwdFilterAlgo_t paddle::operators::SearchAlgorithm<cudnnConvolutionBwdFilterAlgoPerf_t>::Find<float>(paddle::operators::ConvArgs const&, bool, bool, paddle::framework::ExecutionContext const&)
5   cudnnGetConvolutionBackwardFilterAlgorithm_v7
6   paddle::framework::SignalHandle(char const*, int)
7   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1634042835 (unix time) try "date -d @1634042835" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3e80000336d) received by PID 13165 (TID 0x7fa3ac6a60c0) from PID 13165 ***]
```
但是，其实都存在。
```none
(base) jim@jim-HP:~$ locate libcudnn_cnn_train.so.8
/home/jim/Downloads/cuda cudnn/cuda/lib64/libcudnn_cnn_train.so.8
/home/jim/Downloads/cuda cudnn/cuda/lib64/libcudnn_cnn_train.so.8.2.2
/home/jim/miniconda3/envs/pp21/lib/libcudnn_cnn_train.so.8
/home/jim/miniconda3/envs/pp21/lib/libcudnn_cnn_train.so.8.1.0
/home/jim/miniconda3/pkgs/cudnn-8.1.0.77-h90431f1_0/lib/libcudnn_cnn_train.so.8
/home/jim/miniconda3/pkgs/cudnn-8.1.0.77-h90431f1_0/lib/libcudnn_cnn_train.so.8.1.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.2
(base) jim@jim-HP:~$ locate libcudnn_ops_train.so.8
/home/jim/Downloads/cuda cudnn/cuda/lib64/libcudnn_ops_train.so.8
/home/jim/Downloads/cuda cudnn/cuda/lib64/libcudnn_ops_train.so.8.2.2
/home/jim/miniconda3/envs/pp21/lib/libcudnn_ops_train.so.8
/home/jim/miniconda3/envs/pp21/lib/libcudnn_ops_train.so.8.1.0
/home/jim/miniconda3/pkgs/cudnn-8.1.0.77-h90431f1_0/lib/libcudnn_ops_train.so.8
/home/jim/miniconda3/pkgs/cudnn-8.1.0.77-h90431f1_0/lib/libcudnn_ops_train.so.8.1.0
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.2
```
## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddle 2.1.2
PaddleDetection release/2.2版本

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
还使用PaddleSeg2.2版本，并且同一环境，paddleseg是正常训练的，今天还进行了训练测试，如下图。
![Uploading 6891634021803_.pic_hd.jpg…]()
但是，使用paddledetection进行训练却出现error。
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
ubuntu18.04
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
Python 3.8.11 (default, Aug  3 2021, 15:09:35)
[GCC 7.5.0] :: Anaconda, Inc. on linux
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA 11.4
cuDNN 8.2

如果您的issue是关于安装或环境，您可以先查询[安装文档](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL_cn.md)尝试解决~

If your issue looks like an installation issue / environment issue,
please first try to solve it yourself with the instructions in
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.1/docs/tutorials/INSTALL.md

**Comment by wangxinxin08** [comment]
训练环境没有搭建好，使用export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH来导入相关的so文件，/usr/local/cuda/lib64实际软链接到的是/usr/local/cuda-10.2/targets/x86_64-linux/lib/

**Comment by yuanjim** [comment]
> 训练环境没有搭建好，使用export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH来导入相关的so文件，/usr/local/cuda/lib64实际软链接到的是/usr/local/cuda-10.2/targets/x86_64-linux/lib/

谢谢帮助。
我做了变量路径修改：
```none
(base) jim@jim-HP:~$ vim ~/.bashrc
(base) jim@jim-HP:~$ source ~/.bashrc
```
修改后的bashrc：
```none
# <<< conda initialize <<<
export PATH="/usr/local/cuda/bin:$PATH"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
```
但是，问题依旧。ε=(´ο｀*)))唉，继续寻找解决办法。奇怪的是，为啥paddleseg就可以正常训练。

**Comment by yuanjim** [comment]
试了下新搭建一个环境，可以正常训练了。万能的重启。
```none
重新搭建环境：
conda create -n pp212 python==3.7

安装paddle，对应的是cuda10.2：
python -m pip install paddlepaddle-gpu -i https://mirror.baidu.com/pypi/simple

安装依赖，建议单个安装，以requirement方式容易卡壳，例如：
pip install cython_bbox -i https://mirror.baidu.com/pypi/simple
```
