### ISSUE TITLE
[Other General Issues]tools/infer.py 提示显存不足，但模型tools/train.py能够正常训练，tools/eval.py验证能正常运行

### ISSUE THREAD

**Issue by qingchunnianshao** [PaddlePaddle/PaddleDetection#5020]
## 描述问题/Describe the bug

使用paddleDetection fastercnn 训练自己的数据集，tool/train.py 训练能够正常完成 tool/eval.py 也能正常验证
但是tool/infer.py 测试数据时需要分配大量显存导致显存空间不足无法预测。

执行tools/eval.py能够正常执行log如下：
[12/28 20:23:34] ppdet.utils.checkpoint INFO: Finish loading model weights: output/faster_rcnn_r50_1x_voc_bydouble/model_final.pdparams
[12/28 20:23:35] ppdet.engine INFO: Eval iter: 0
[12/28 20:24:23] ppdet.engine INFO: Eval iter: 100
[12/28 20:24:45] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[12/28 20:24:45] ppdet.metrics.metrics INFO: mAP(0.50, integral) = 48.96%
[12/28 20:24:45] ppdet.engine INFO: Total sample number: 144, averge FPS: 2.0303356352317237

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```none
请填写命令/A placeholder for the command.
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

有调整过代码以及配置文件，调整了fasterrcnn 的 骨干网络resnet50的输入，从三通道改为单通道图，图像大小进行固定为2500*2500
了解自己修改的代码以及配置文件，目前问题就是能正常训练，验证，但是到预测tool/infer.py时提示显存不够，

faster_reader.yml TestReader 如下，已经调整过模型，将三通道的图像修改为使用单通道图像，batch_size 设置也为1
worker_num: 1
TrainReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [2500, 2500], keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.45095402013249447], std: [0.16771371238019508]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1}
  batch_size: 1
  shuffle: true
  drop_last: true
  collate_batch: false
EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [2500, 2500], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.45095402013249447], std: [0.16771371238019508]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1}
  batch_size: 1
  shuffle: false
  drop_last: false
TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [2500, 2500], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.45095402013249447], std: [0.16771371238019508]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1}
  batch_size: 1
  shuffle: false
  drop_last: false

3. 您使用的数据集是？/What dataset did you use?
我使用的是自己的数据集，已经调整为VOC格式，目前能正常训练并且收敛，就是在测试阶段显卡会需要分配更多显存空间，不知道问题在什么地方。

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.

W1228 19:56:34.346077 17094 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.1
W1228 19:56:34.349443 17094 device_context.cc:465] device: 0, cuDNN Version: 8.0.
W1228 19:56:35.286401 17094 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.1, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
[12/28 19:56:42] ppdet.utils.checkpoint INFO: Finish loading model weights: output/faster_rcnn_r50_1x_voc_bydouble/model_final.pdparams
[12/28 19:56:42] train INFO: Found 220 inference images in total.
Traceback (most recent call last):
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/infer.py", line 170, in <module>
    main()
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/infer.py", line 166, in main
    run(FLAGS, cfg)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/tools/infer.py", line 130, in run
    trainer.predict(
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/engine/trainer.py", line 517, in predict
    outs = self.model(data)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/architectures/meta_arch.py", line 72, in forward
    out = self.get_pred()
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/architectures/faster_rcnn.py", line 104, in get_pred
    bbox_pred, bbox_num = self._forward()
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/architectures/faster_rcnn.py", line 82, in _forward
    preds, _ = self.bbox_head(body_feats, rois, rois_num, None)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/heads/bbox_head.py", line 242, in forward
    bbox_feat = self.head(rois_feat)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/backbones/resnet.py", line 619, in forward
    y = self.res5(roi_feat)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/backbones/resnet.py", line 427, in forward
    block_out = block(block_out)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/backbones/resnet.py", line 366, in forward
    out = self.branch2c(out)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/Downloads/PaddleDetection-release-2.3/ppdet/modeling/backbones/resnet.py", line 133, in forward
    out = self.norm(out)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/tjzn/anaconda3/lib/python3.8/site-packages/paddle/fluid/dygraph/nn.py", line 1347, in forward
    batch_norm_out, _, _, _, _, _ = _C_ops.batch_norm(
SystemError: (Fatal) Operator batch_norm raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 382.812744MB memory on GPU 0, 11.599365GB memory has been allocated and available memory is only 176.062500MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 

 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:79)
. (at /paddle/paddle/fluid/imperative/tracer.cc:221)

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：

paddle版本：2.2.1
paddleDetection 版本2.3.0

2. 如您在使用PaddleDetection的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号/ Please provide the version of any other related tools/products used, such as the version of PaddleServing and etc：
 无
3. 请提供您使用的操作系统信息，如Linux/Windows/MacOS /Please provide the OS information, e.g., Linux：
操作系统Ubuntu18.04
4. 请问您使用的Python版本是？/ Please provide the version of Python you used.
python版本3.8.5
5. 请问您使用的CUDA/cuDNN的版本号是？/ Please provide the version of CUDA/cuDNN you used.
CUDA 版本11.2  
cuDNN 版本 8.0
显卡为Geforce RTX3060  12G 显存

期待回复

**Comment by heavengate** [comment]
你好，你的显存多大呢，是否是卡上面有其他任务占了显存，一般训练能跑的话infer应该没问题的

**Comment by qingchunnianshao** [comment]
显卡是12G的，没有其他程序在这个卡上运行，是执行infer.py的时候监控显卡使用情况发现在测试的时候显存分配超出12G，所以现在比较疑惑，为什么能够训练，验证就是测试的时候提示显存不够

**Comment by qingchunnianshao** [comment]
> 你好，你的显存多大呢，是否是卡上面有其他任务占了显存，一般训练能跑的话infer应该没问题的

你好能协助帮忙分析一下问题吧,为了防止有其他程序占用显存,也进行了重启操作,对程序也进行了单步调试,基本上定位就是outs = self.model(data) 执行预测的这句话时,显存上涨明显

**Comment by Victoria-1** [comment]
我用来训练关键点检测也遇到同样的问题，能正常训练，但用infer推断时内存分配出错

**Comment by Victoria-1** [comment]
我改成use_gpu=false, 用cpu去infer是可以的，用gpu依然提示出错

**Comment by qingchunnianshao** [comment]
> 我改成use_gpu=false, 用cpu去infer是可以的，用gpu依然提示出错

我的问题是加一个 with paddle.no_grad()之后就好了，只是model.eval() 好像不行
with paddle.no_grad():
    self.status['mode'] = 'test'
     self.model.eval()
     if self.cfg.get('print_flops', False):
          self._flops(loader)
        results = []
        for step_id, data in enumerate(loader):
            self.status['step_id'] = step_id
            # forward
            outs = self.model(data)

**Comment by Liqq1** [comment]
> > 我改成use_gpu=false, 用cpu去infer是可以的，用gpu依然提示出错
> 
> 我的问题是加一个 with paddle.no_grad()之后就好了，只是model.eval() 好像不行 with paddle.no_grad(): self.status['mode'] = 'test' self.model.eval() if self.cfg.get('print_flops', False): self._flops(loader) results = [] for step_id, data in enumerate(loader): self.status['step_id'] = step_id # forward outs = self.model(data)

您好，请问你这段代码是加在哪个文件里的呀
