### ISSUE TITLE
运行报错CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example

### ISSUE THREAD

**Issue by wstchhwp** [PaddlePaddle/PaddleDetection#5073]
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W0107 07:35:36.109134 3202509 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.0
W0107 07:35:36.111485 3202509 device_context.cc:465] device: 0, cuDNN Version: 8.1.
Traceback (most recent call last):
  File "tools/train.py", line 126, in <module>
    main()
  File "tools/train.py", line 122, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 69, in run
    trainer = Trainer(cfg, mode='train')
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/engine/trainer.py", line 77, in __init__
    self.model = create(cfg.architecture)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/core/workspace.py", line 233, in create
    cls_kwargs.update(cls.from_config(config, **kwargs))
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/modeling/architectures/faster_rcnn.py", line 56, in from_config
    backbone = create(cfg['backbone'])
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/core/workspace.py", line 277, in create
    return cls(**cls_kwargs)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/modeling/backbones/swin_transformer.py", line 621, in __init__
    norm_layer=norm_layer if self.patch_norm else None)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddledet-2.3.0-py3.7.egg/ppdet/modeling/backbones/swin_transformer.py", line 535, in __init__
    in_chans, embed_dim, kernel_size=patch_size, stride=patch_size)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 656, in __init__
    data_format=data_format)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 424, in create_parameter
    default_initializer)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 378, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3137, in create_parameter
    initializer(param, self)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 366, in __call__
    stop_gradient=True)
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3167, in append_op
    kwargs.get("stop_gradient", False))
  File "/home/easyits/anaconda3/envs/paddledet/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External) CUBLAS error(7).
  [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at /paddle/paddle/fluid/platform/cuda_helper.h:107)
  [operator < gaussian_random > error]

**Comment by nemonameless** [comment]
#5071 
运行命令以及环境版本信息也请发下？谢谢

**Comment by Septembit** [comment]
你好 我也相同的情况
 GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 11.0
 cuDNN Version: 7.6.
请问解决了吗

**Comment by Septembit** [comment]
解决了是安装的版本跟cuda版本不匹配

**Comment by chenjw1009** [comment]
是的，CUDA：11.0 ，cudnn：8.0.5
报错是版本不匹配。

**Comment by ChiLincoln** [comment]
> #5071 运行命令以及环境版本信息也请发下？谢谢
paddle.utils.run_check()测试的化境显示成功
paddle==2.2.2
 GPU Compute Capability: 8.6, Driver API Version: 11.1, Runtime API Version: 11.0
W0322 09:32:37.436890  3921 device_context.cc:465] device: 0, cuDNN Version: 8.1.

**Comment by ChiLincoln** [comment]
> 是的，CUDA：11.0 ，cudnn：8.0.5 报错是版本不匹配。

我已经把环境升级到cuda11.1,cudnn8.1.1.还是有相同报错.然后重新安装了cuda runtime11.0后,报错改变了.正在检查代码

**Comment by wstchhwp** [comment]
> > 是的，CUDA：11.0 ，cudnn：8.0.5 报错是版本不匹配。
> 
> 我已经把环境升级到cuda11.1,cudnn8.1.1.还是有相同报错.然后重新安装了cuda runtime11.0后,报错改变了.正在检查代码

可能是数据集中那张图片有问题

**Comment by ChiLincoln** [comment]
> 

对,是配置文件里图片尺寸的问题,已解决.

**Comment by peggyxpxu** [comment]
> 
请问能告知一下具体是什么问题，怎么解决吗？我也遇到了这个问题

**Comment by wstchhwp** [comment]
> 
图片和标签可能存在问题

**Comment by peggyxpxu** [comment]
> > 
> 
> 图片和标签可能存在问题

具体是什么问题，应该怎么修改呢

**Comment by peggyxpxu** [comment]
> > 
> 
> 对,是配置文件里图片尺寸的问题,已解决.

请问能告知一下具体是什么问题，怎么解决吗？我也遇到了这个问题

**Comment by starplanet** [comment]
不是数据集的问题。选用picodet s系列模型以及m 320模型就会报这个错误，选用m 460就可以。不知道是不是跟我num_class为1是否有关？

**Comment by qinhuangdaoStation** [comment]
1、从经验来看，以下配置可以解决这个问题：（以下组合为个人尝试之后的解决方式，也可以自行探索其他可行的版本组合）（安装的时候请注意以下顺序）
（1）python=3.9（这个很重要，3.11和3.8都有问题）
（2）cudatoolkit=11.7（这个也很重要，cudatoolkit=其他版本都有问题）
（3）paddlenlp=2.8.1这个是我完成上述步骤之后再安装的
2、然后，直接使用[官方安装方式](https://www.paddlepaddle.org.cn/documentation/docs/zh/2.6/install/conda/linux-conda.html)即可，其他依赖包再后续安装
conda install paddlepaddle-gpu==2.6.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge
3、cudnn我没有单独安装，据说安装cudatoolkit的时候会包含
