### ISSUE TITLE
使用多卡训练问题：训练卡住 [Other General Issues]

### ISSUE THREAD

**Issue by pynsigrid** [PaddlePaddle/PaddleDetection#5435]
## 描述问题/Describe the bug
使用paddleDetection训练自己的数据集，使用同样的数据和配置文件，单卡可以训练，多卡训练在load pretrain model之后会卡住

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```bash
# 多卡
python -m paddle.distributed.launch --gpus 0,1,2,3 tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_coco_v20.yml --eval --use_vdl True 
# 单卡：可以成功
python tools/train.py -c configs/ppyolo/ppyolov2_r50vd_dcn_coco_v20.yml --eval --use_vdl True 
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

训练自己的数据集，只是修改了数据集路径、batch_size、和输入图片大小
configs/ppyolo/_base_/ppyolov2_reader.yml: 
```
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2} # modified
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 12 # modified
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2} # modified
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8 # modified

```

5. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
1. 终端输出：
```
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 0,1,2,3
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: tools/train.py
training_script_args: ['-c', 'configs/ppyolo/ppyolov2_r50vd_dcn_spore_coco_v20.yml', '--eval', '--use_vdl', 'True']
worker_num: None
workers: 
------------------------------------------------
launch train in GPU mode!
launch proc_id:3735921 idx:0
launch proc_id:3735926 idx:1
launch proc_id:3735931 idx:2
launch proc_id:3735938 idx:3
/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:476: DeprecationWarning: invalid escape sequence \_
  """
/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:1277: DeprecationWarning: invalid escape sequence \l
  """
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0323 10:56:39.002599 3735921 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0323 10:56:40.937754 3735921 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.6, Runtime API Version: 11.2
W0323 10:56:40.958221 3735921 device_context.cc:465] device: 0, cuDNN Version: 8.3.
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[03/23 10:56:59] ppdet.utils.checkpoint INFO: ['backbone.res5.res5a.branch2b.norm._mean', 'backbone.res5.res5a.branch2b.norm._variance', 'backbone.res5.res5b.branch2b.norm.bias', 'backbone.res5.res5b.branch2b.norm.weight', 'backbone.res5.res5c.branch2c.conv.weight', 'backbone.res5.res5c.branch2c.norm._mean'] in pretrained weight is not used in the model, and its will not be loaded
[03/23 10:56:59] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/LAB/huzy/.cache/paddle/weights/ResNet50_vd_ssld_pretrained.pdparams

```
2. workerlog.1
```
/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:476: DeprecationWarning: invalid escape sequence \_
  """
/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:1277: DeprecationWarning: invalid escape sequence \l
  """
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0323 10:56:39.002599 3735921 nccl_context.cc:74] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0323 10:56:40.937754 3735921 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.6, Runtime API Version: 11.2
W0323 10:56:40.958221 3735921 device_context.cc:465] device: 0, cuDNN Version: 8.3.
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
[03/23 10:56:59] ppdet.utils.checkpoint INFO: ['backbone.res5.res5a.branch2b.norm._mean', 'backbone.res5.res5a.branch2b.norm._variance', 'backbone.res5.res5b.branch2b.norm.bias', 'backbone.res5.res5b.branch2b.norm.weight', 'backbone.res5.res5c.branch2c.conv.weight', 'backbone.res5.res5c.branch2c.norm._mean'] in pretrained weight is not used in the model, and its will not be loaded
[03/23 10:56:59] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/LAB/huzy/.cache/paddle/weights/ResNet50_vd_ssld_pretrained.pdparams


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
1   paddle::imperative::Tracer::TraceOp(std::string const&, paddle::imperative::NameVarBaseMap const&, paddle::imperative::NameVarBaseMap const&, paddle::framework::AttributeMap, paddle::platform::Place const&, bool, std::map<std::string, std::string, std::less<std::string >, std::allocator<std::pair<std::string const, std::string > > > const&)
2   std::shared_ptr<paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type> paddle::imperative::PrepareData<paddle::imperative::VarBase>(paddle::framework::OperatorWithKernel const&, paddle::imperative::details::NameVarMapTrait<paddle::imperative::VarBase>::Type const&, paddle::framework::OpKernelType const&)
3   paddle::framework::TransformData(paddle::framework::OpKernelType const&, paddle::framework::OpKernelType const&, paddle::framework::Tensor const&, paddle::framework::Tensor*)
4   paddle::framework::TransDataDevice(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
5   paddle::framework::TensorCopySync(paddle::framework::Tensor const&, paddle::platform::Place const&, paddle::framework::Tensor*)
6   void paddle::memory::Copy<paddle::platform::CUDAPlace, paddle::platform::CUDAPinnedPlace>(paddle::platform::CUDAPlace, void*, paddle::platform::CUDAPinnedPlace, void const*, unsigned long, CUstream_st*)
7   paddle::platform::GpuMemcpySync(void*, void const*, unsigned long, cudaMemcpyKind)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648005016 (unix time) try "date -d @1648005016" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x386700390158) received by PID 3735921 (TID 0x7f5d4e6794c0) from PID 3735896 ***]


```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
paddlepaddle-gpu=2.2.2.post112, PaddleDetection is default, cuDNN=8.3, nccl checked:

```

```
Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0323 11:10:39.810568 3739188 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.6, Runtime API Version: 11.2
W0323 11:10:39.820714 3739188 device_context.cc:465] device: 0, cuDNN Version: 8.3.
PaddlePaddle works well on 1 GPU.
```

**Comment by nemonameless** [comment]
建议workerlog.2 3 等都看下，可能是爆显存了，可以减小bs或输入尺度。
另外要用单尺度- Resize: {}，就得注释掉BatchRandomResize。

**Comment by pynsigrid** [comment]
> 建议workerlog.2 3 等都看下，可能是爆显存了，可以减小bs或输入尺度。 另外要用单尺度- Resize: {}，就得注释掉BatchRandomResize。

谢谢您的帮助，问题基本解决了。应该就是显存占满的原因。
另外请问 worklog怎么看出是什么错误原因呢？
👇worklog3:
```
DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0323 11:32:48.671030 4029053 gen_comm_id_helper.cc:190] Server listening on: 127.0.0.1:47719 successful.
I0323 11:32:51.683522 4029053 nccl_context.cc:74] init nccl context nranks: 4 local rank: 3 gpu id: 3 ring id: 0
W0323 11:32:53.102552 4029053 device_context.cc:447] Please NOTE: device: 3, GPU Compute Capability: 8.0, Driver API Version: 11.6, Runtime API Version: 11.2
W0323 11:32:53.116132 4029053 device_context.cc:465] device: 3, cuDNN Version: 8.3.
loading annotations into memory...
Done (t=0.08s)
creating index...
index created!
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::CheckNextStatus()
1   paddle::pybind::MultiDeviceFeedReader<paddle::operators::reader::LoDTensorBlockingQueue>::WaitFutures(std::__exception_ptr::exception_ptr*)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1648006408 (unix time) try "date -d @1648006408" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3867003d7a50) received by PID 4029053 (TID 0x7fc40a4bd4c0) from PID 4029008 ***]

/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:476: DeprecationWarning: invalid escape sequence \_
  """
/home/LAB/huzy/span/paddle/PaddleDetection/ppdet/modeling/ops.py:1277: DeprecationWarning: invalid escape sequence \l
  """
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
I0323 11:34:51.378926 4029787 gen_comm_id_helper.cc:190] Server listening on: 127.0.0.1:36369 successful.
I0323 11:34:54.338200 4029787 nccl_context.cc:74] init nccl context nranks: 4 local rank: 3 gpu id: 3 ring id: 0
W0323 11:34:55.760634 4029787 device_context.cc:447] Please NOTE: device: 3, GPU Compute Capability: 8.0, Driver API Version: 11.6, Runtime API Version: 11.2
W0323 11:34:55.776332 4029787 device_context.cc:465] device: 3, cuDNN Version: 8.3.
loading annotations into memory...
Done (t=0.06s)
creating index...
index created!
/home/LAB/huzy/.conda/envs/pd/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
```
