### ISSUE TITLE
目标跟踪预测报错，按照教程运行报错了

### ISSUE THREAD

**Issue by XuLei0** [PaddlePaddle/PaddleDetection#6565]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有报过同样bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### bug描述 Describe the Bug

执行命令：CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/jde/jde_darknet53_30e_1088x608.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/jde_darknet53_30e_1088x608.pdparams --video_file=E:/PaddleDetection/dataset/my_test_data/videos/MOT16.mp4  --save_videos

cpu执行就可以

Traceback (most recent call last):
  File "E:/PaddleDetection/tools/infer_mot.py", line 150, in <module>
    main()
  File "E:/PaddleDetection/tools/infer_mot.py", line 146, in main
    run(FLAGS, cfg)
  File "E:/PaddleDetection/tools/infer_mot.py", line 100, in run
    tracker.mot_predict_seq(
  File "E:\PaddleDetection\ppdet\engine\tracker.py", line 544, in mot_predict_seq
    results, nf, ta, tc = self._eval_seq_jde(
  File "E:\PaddleDetection\ppdet\engine\tracker.py", line 147, in _eval_seq_jde
    pred_dets, pred_embs = self.model(data)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "E:\PaddleDetection\ppdet\modeling\architectures\jde.py", line 110, in get_pred
    return self._forward()
  File "E:\PaddleDetection\ppdet\modeling\architectures\jde.py", line 68, in _forward
    det_outs = self.detector(self.inputs)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PaddleDetection\ppdet\modeling\architectures\meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "E:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 128, in get_pred
    return self._forward()
  File "E:\PaddleDetection\ppdet\modeling\architectures\yolo.py", line 99, in _forward
    boxes_idx, bbox, bbox_num, nms_keep_idx = self.post_process(
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\PaddleDetection\ppdet\modeling\post_process.py", line 459, in forward
    bbox_pred, bbox_num, nms_keep_idx = self.nms(
  File "E:\PaddleDetection\ppdet\modeling\layers.py", line 488, in __call__
    return ops.multiclass_nms(bboxes, score, **kwargs)
  File "E:\PaddleDetection\ppdet\modeling\ops.py", line 725, in multiclass_nms
    helper.append_op(
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\layer_helper.py", line 44, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\framework.py", line 3599, in append_op
    _dygraph_tracer().trace_op(type,
  File "D:\Miniconda\envs\Paddle\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 307, in trace_op
    self.trace(type, inputs, outputs, attrs,
OSError: (External) CUDA error(719), unspecified launch failure. 
  [Hint: 'cudaErrorLaunchFailure'. An exception occurred on the device while executing a kernel. Common causes include dereferencing an invalid device pointerand accessing out of bounds shared memory. Less common cases can be system specific - more information about these cases canbe found in the system specific user guide. This leaves the process in an inconsistent state and any further CUDA work willreturn the same error. To continue using CUDA, the process must be terminated and relaunched.] (at ..\paddle\phi\backends\gpu\gpu_context.cc:435)
  [operator < multiclass_nms3 > error]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]
Error: ../paddle/phi/kernels/funcs/gather.cu.h:67 Assertion `index_value >= 0 && index_value < input_dims[j]` failed. The index is out of bounds, please check whether the dimensions of index and input meet the requirements. It should be less than [54264] and greater than or equal to 0, but received [0]

### 复现环境 Environment

- PaddlePaddle 2.31.post116
- cuda 11.6
- cudnn 8.4
- python 3.8

### 是否愿意提交PR Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by nemonameless** [comment]
收到会尽快排查。可以再试试你的环境下跑通用检测模型如ppyoloe的预测有没有问题。以及跟踪建议使用fairmot或bytetrack。

**Comment by XuLei0** [comment]
> 收到会尽快排查。可以再试试你的环境下跑通用检测模型如ppyoloe的预测有没有问题。以及跟踪建议使用fairmot或bytetrack。

通用检测模型都可以，跟踪的不行
我只是预测一个视频，没有下载目标跟踪的数据集来训练，用的是你们提供的一个 权重 https://paddledet.bj.bcebos.com/models/mot/jde_darknet53_30e_1088x608.pdparams，也就是dataset/mot这个文件夹没有添加数据集，直接运行命令：
CUDA_VISIBLE_DEVICES=0 python tools/infer_mot.py -c configs/mot/jde/jde_darknet53_30e_576x320.yml -o weights=https://paddledet.bj.bcebos.com/models/mot/jde_darknet53_30e_576x320.pdpa
rams --video_file=E:/PaddleDetection/dataset/my_test_data/videos/MOT16.mp4 --save_videos
这样可以预测吗？

**Comment by jklkid** [comment]
我和你环境一样，也有这个问题，而且不光推理，训练也会出错，按照官方流程，用MOT16会出现ValueError: Target -4814338588170977684 is out of lower bound. 
我推测可能虽然推出了兼容cuda11.6的版本，但可能在跟踪这块还存在问题

**Comment by XuLei0** [comment]
> 

我现在除了JDE的不行，另外几个都可以跑了，问题出在：
layers.py 有个 _topk函数，里面的 topk_ys 和 topk_xs 的计算，貌似 paddle 没有这个 // 整除的功能,或者这个功能出错了吧，我把它改成了 topk_ys = paddle.cast(topk_inds / width, 'int64')，就可以了。
还有后面的 topk_clses = paddle.cast(paddle.floor_divide(topk_ind, k_t), 'float32')
貌似也没有 paddle.floor_diride() 或者有问题，我也是把他改成了
topk_clses = paddle.cast(paddle.cast(topk_ind / k_t, 'int64'), 'float32')
改完这些 FairMot，DeepSort, ByteTrack 都可以跑了

**Comment by XuLei0** [comment]
> 我和你环境一样，也有这个问题，而且不光推理，训练也会出错，按照官方流程，用MOT16会出现ValueError: Target -4814338588170977684 is out of lower bound. 我推测可能虽然推出了兼容cuda11.6的版本，但可能在跟踪这块还存在问题

我现在除了JDE的不行，另外几个都可以跑了，问题出在：
layers.py 有个 _topk函数，里面的 topk_ys 和 topk_xs 的计算，貌似 paddle 没有这个 // 整除的功能,或者这个功能出错了吧，我把它改成了 topk_ys = paddle.cast(topk_inds / width, 'int64')，就可以了。
还有后面的 topk_clses = paddle.cast(paddle.floor_divide(topk_ind, k_t), 'float32')
貌似也没有 paddle.floor_diride() 或者有问题，我也是把他改成了
topk_clses = paddle.cast(paddle.cast(topk_ind / k_t, 'int64'), 'float32')
改完这些 FairMot，DeepSort, ByteTrack 都可以跑了

**Comment by jklkid** [comment]
> 

我按照你的方式改了一下，发现还是无法运行，训练部分还是存在ValueError: Target -4814338588170977684 is out of lower bound.问题，我怀疑是标签读取出错了，并且时环境包里的代码问题，你训练时有没有碰到这个情况。
推理部分则是从OSError: (External) CUDA error(719), unspecified launch failure.问题变成了ValueError: (InvalidArgument) The value (4) of the non-singleton dimension does not match the corresponding value (500) in shape for expand_v2 op.你在改的时候有遇到这个问题吗？
还有你在复现时是在win还是在linux上的？

**Comment by XuLei0** [comment]
> > 
> 
> 我按照你的方式改了一下，发现还是无法运行，训练部分还是存在ValueError: Target -4814338588170977684 is out of lower bound.问题，我怀疑是标签读取出错了，并且时环境包里的代码问题，你训练时有没有碰到这个情况。 推理部分则是从OSError: (External) CUDA error(719), unspecified launch failure.问题变成了ValueError: (InvalidArgument) The value (4) of the non-singleton dimension does not match the corresponding value (500) in shape for expand_v2 op.你在改的时候有遇到这个问题吗？ 还有你在复现时是在win还是在linux上的？

在 windows上跑的 JDE 目标跟踪，paddle.nonzero() 这个有问题，找出来的索引竟然会越界，然后报这个错误
具体代码在 ppdet/modeling/layers.py 的 def __call__ 函数里面 boxes_idx_over_conf_thr = paddle.nonzero(a)，你可以去看看debug看看 这个 boxed_idx_over_conf_thr 的值是不是特别大，越界了

**Comment by jklkid** [comment]
> > > 
> > 
> > 
> > 我按照你的方式改了一下，发现还是无法运行，训练部分还是存在ValueError: Target -4814338588170977684 is out of lower bound.问题，我怀疑是标签读取出错了，并且时环境包里的代码问题，你训练时有没有碰到这个情况。 推理部分则是从OSError: (External) CUDA error(719), unspecified launch failure.问题变成了ValueError: (InvalidArgument) The value (4) of the non-singleton dimension does not match the corresponding value (500) in shape for expand_v2 op.你在改的时候有遇到这个问题吗？ 还有你在复现时是在win还是在linux上的？
> 
> 在 windows上跑的 JDE 目标跟踪，paddle.nonzero() 这个有问题，找出来的索引竟然会越界，然后报这个错误 具体代码在 ppdet/modeling/layers.py 的 def **call** 函数里面 boxes_idx_over_conf_thr = paddle.nonzero(a)，你可以去看看debug看看 这个 boxed_idx_over_conf_thr 的值是不是特别大，越界了

推理部分这个问题解决了，但是训练阶段还是有问题，你的跟踪能训练吗？按照他的教程？我按照教程会出现：
Traceback (most recent call last):
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 177, in <module>
    main()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 173, in main
    run(FLAGS, cfg)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\tools\train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\engine\trainer.py", line 454, in train
    outputs = model(data)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 99, in get_loss    loss = self._forward()
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\architectures\fairmot.py", line 78, in _forward    reid_loss = self.reid(neck_feat, self.inputs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 115, in forward
    loss = self.get_loss(reid_feat, inputs)
  File "D:\Project_pptracking\PaddleDetection-release-2.4\ppdet\modeling\reid\fairmot_embedding_head.py", line 163, in get_loss
    loss = self.reid_loss(logit, target)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\layer\loss.py", line 397, in forward
    ret = paddle.nn.functional.cross_entropy(
  File "D:\Anaconda3\envs\pp-tracking\lib\site-packages\paddle\nn\functional\loss.py", line 1722, in cross_entropy
    raise ValueError("Target {} is out of upper bound.".format(
ValueError: Target 4578971296541297966 is out of upper bound.
这个错误。

**Comment by nemonameless** [comment]
win下建议安装paddle2.2.2版本

**Comment by nemonameless** [comment]
win下请安装最新develop版本的paddle。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html
