### ISSUE TITLE
The third-party dynamic library

### ISSUE THREAD

**Issue by yin-silly** [PaddlePaddle/PaddleDetection#7089]
### 问题描述 Please describe your issue

>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W1010 12:46:29.882460  7242 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 10.2
W1010 12:46:29.887960  7242 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
W1010 12:46:29.989503  7242 dynamic_loader.cc:305] The third-party dynamic library (libcuda.so) that Paddle depends on is not configured correctly. (error code is libcuda.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX;

locate libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.460.80
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.460.80
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so
/usr/local/cuda-10.0/doc/man/man7/libcuda.so.7
/usr/local/cuda-10.0/lib64/stubs/libcuda.so
/usr/local/cuda-10.1/doc/man/man7/libcuda.so.7
/usr/local/cuda-10.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.1/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/share/man/man7/libcuda.so.7
/usr/share/man/man7/libcuda.so.7.gz

help!!!

**Comment by yin-silly** [comment]
nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

**Comment by XYZ-916** [comment]
请问你安装的paddle版本是？

**Comment by yin-silly** [comment]
2.3.2，已经解决了  这个包位置在lib/stubs/下，需要手动把它复制到lib/下
奇怪的是locate libcuda.so并没有找到这个包

**Comment by a-3isa** [comment]
which package?

**Comment by DormouseLi** [comment]
My libcuda.so is in /usr/local/cuda-12.8/targets/x86_64-linux/lib/stubs/. I copy the file to the   /usr/local/cuda-12.8/targets/x86_64-linux/lib/ and fix the problem.
