### ISSUE TITLE
使用Mask_rcnn训练模型之后infer运行失败内存溢出

### ISSUE THREAD

**Issue by knowledge-things** [PaddlePaddle/PaddleDetection#7191]
### 问题确认 Search before asking

- [X] 我已经查询[历史issue](https://github.com/PaddlePaddle/PaddleDetection/issues)，没有发现相似的bug。I have searched the [issues](https://github.com/PaddlePaddle/PaddleDetection/issues) and found no similar bug report.

### Bug组件 Bug Component

Inference

### Bug描述 Describe the Bug

模型训练之后进行infer内存溢出，显卡并无其他任务运行,预测图片总数约500Mb
```shell
python deploy/python/infer.py --model_dir=./inference_model/mask_rcnn_r50_vd_fpn_2x_coco/ --image_dir=output/500A --output_dir=output/500A_TEST --device=gpu
```
log日志如下
```shell
Traceback (most recent call last):
  File "deploy/python/infer.py", line 909, in <module>
    main()
  File "deploy/python/infer.py", line 882, in main
    img_list, FLAGS.run_benchmark, repeats=100, save_file=save_file)
  File "deploy/python/infer.py", line 278, in predict_image
    result = self.predict()
  File "deploy/python/infer.py", line 206, in predict
    self.predictor.run()
RuntimeError: ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 2.324581GB memory on GPU 0, 6.075684GB memory has been allocated and available memory is only 1.711487GB.
```

### 复现环境 Environment

- OS:Ubuntu20
- DockerImage:paddlecloud/paddledetection:2.4-gpu-cuda11.2-cudnn8-latest
- Cuda:11.2
- paddlepaddle-gpu:2.3.0.post112

### Bug描述确认 Bug description confirmation

- [X] 我确认已经提供了Bug复现步骤、代码改动说明、以及环境信息，确认问题是可以复现的。I confirm that the bug replication steps, code change instructions, and environment information have been provided, and the problem can be reproduced.

### 是否愿意提交PR？ Are you willing to submit a PR?

- [ ] 我愿意提交PR！I'd like to help by submitting a PR!

**Comment by knowledge-things** [comment]
运行infer之前GPU信息
```shell
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| N/A   41C    P8     9W /  N/A |    110MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

```

**Comment by wangxinxin08** [comment]
使用上述的环境和命令进行测试，并没有出现显存溢出的现象，你的显存是一直增长的吗？

**Comment by knowledge-things** [comment]
> 使用上面的环境和命令进行测试，并没有出现显着存在的现象，你的显存是一直在增长的吗？

是的显存一直在增长，边训练边评估也是失败的，根据官方实例修改了部分训练参数，
`mask_fpn_reader.yml`
```yml
worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
  - RandomFlip: {prob: 0.5}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: true

EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: false


TestReader: #测试数据读取,有些前处理需要保持一致
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  shuffle: false
  drop_last: false
```
训练命令
```shell
python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar -o use_gpu=true pretrain_weights=output/mask_rcnn_r50_vd_fpn_2x_coco/model_final --eval
```
报错信息
```
[10/26 09:34:40] ppdet.engine INFO: Eval iter: 0
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 512, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 535, in _eval_with_loader
    outs = self.model(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 133, in get_pred
    bbox_pred, bbox_num, mask_pred = self._forward()
  File "/home/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 119, in _forward
    origin_shape)
  File "/home/PaddleDetection/ppdet/modeling/post_process.py", line 265, in __call__
    bboxes_i[:, 2:], im_h, im_w)
  File "/home/PaddleDetection/ppdet/modeling/post_process.py", line 220, in paste_mask
    grid = paddle.stack([gx, gy], axis=3)
  File "/usr/local/lib/python3.7/dist-packages/paddle/tensor/manipulation.py", line 903, in stack
    return layers.stack(x, axis, name)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/nn.py", line 10397, in stack
    return _C_ops.stack(x, 'axis', axis)
SystemError: (Fatal) Operator stack raises an paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError: 

Out of memory error on GPU 0. Cannot allocate 2.373047GB memory on GPU 0, 6.200684GB memory has been allocated and available memory is only 1.586487GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model. 
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
```

**Comment by knowledge-things** [comment]
> 使用上面的环境和命令进行测试，并没有出现显着存在的现象，你的显存是一直在增长的吗？

和输入图片尺寸是否有关系
有如下尺寸：
4608 × 3456
1702 × 1276
4032 × 3024
3264 × 2448

**Comment by wangxinxin08** [comment]
可能和图片大小有关，你试下PaddlePaddle 2.4.0rc或者2.3.2，这个问题应该在新的稳定版解决了。这个页面下有PaddleDetection 2.3.2和2.4.0rc的包https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by knowledge-things** [comment]
> 可能和图片大小有关，你试下PaddlePaddle 2.4.0rc或者2.3.2，这个问题应该在新的稳定版解决了。这个页面下有PaddleDetection 2.3.2和2.4.0rc的包https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

同样的图片使用不加fpn层的进行训练和评估没有问题，您能帮试下mask_rcnn_r50_vd_fpn_2x_coco这个网络模式吗

**Comment by wangxinxin08** [comment]
@knowledge-things 我这里已经试过了用coco预训练评估5000张coco图片没有报错，所以可能和图片大小有关。这种可能是由特定的算子导致的(fpn中)，所以让你试下2.4.0rc或者2.3.2

**Comment by knowledge-things** [comment]
@wangxinxin08 我是直接用的docker PaddleDetection 
nvidia-smi命令显示的是CUDA Version：11.8 
nvcc -V结构是11.2
```shell
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```
我看您发的网址最多支持到11.7我应该选择11.7还是11.2

**Comment by wangxinxin08** [comment]
@knowledge-things nvidia-smi显示的是驱动最大支持的cuda版本，nvcc -V显示的是真实的cuda版本，所以选11.2

**Comment by knowledge-things** [comment]
@wangxinxin08 
paddle更新成功训练报错，是否需要更新工程
```shell
pip install -U paddlepaddle_gpu-2.4.0rc0.post112-cp37-cp37m-linux_x86_64.whl --force-reinstall
λ f32254061961 /home paddle -v
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
<stdin>:3: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
PaddlePaddle 2.4.0-rc0.post112, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
```
执行边训练边评估
```shell
python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar -o use_gpu=true  --eval
```
报错
```
python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar -o use_gpu=true  --eval
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
[10/26 11:55:53] reader WARNING: Shared memory size is less than 1G, disable shared_memory in DataLoader
W1026 11:55:53.876308  9998 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 11.2
W1026 11:55:53.878268  9998 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
[10/26 11:55:55] ppdet.utils.checkpoint INFO: Finish loading model weights: /root/.cache/paddle/weights/ResNet50_vd_pretrained.pdparams
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/PaddleDetection/ppdet/engine/trainer.py", line 454, in train
    outputs = model(data)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 59, in forward
    out = self.get_loss()
  File "/home/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 123, in get_loss
    bbox_loss, mask_loss, rpn_loss = self._forward()
  File "/home/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 93, in _forward
    rois, rois_num, rpn_loss = self.rpn_head(body_feats, self.inputs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 136, in forward
    rois, rois_num = self._gen_proposal(scores, deltas, anchors, inputs)
  File "/home/PaddleDetection/ppdet/modeling/proposal_generator/rpn_head.py", line 205, in _gen_proposal
    im_shape=im_shape[i:i + 1])
  File "/home/PaddleDetection/ppdet/modeling/proposal_generator/proposal_generator.py", line 76, in __call__
    return_rois_num=True)
  File "/home/PaddleDetection/ppdet/modeling/ops.py", line 1128, in generate_proposals
    scores, bbox_deltas, im_shape, anchors, variances, *attrs)
ValueError: (InvalidArgument) generate_proposals_v2(): argument 'Scores' (position 0) must be Tensor, but got Tensor (at /paddle/paddle/fluid/pybind/op_function_common.cc:818)
```

**Comment by wangxinxin08** [comment]
可以更新下PaddleDetection代码到2.5

**Comment by knowledge-things** [comment]
@wangxinxin08 感谢支持🙏第一轮epoch后eval成功了。

**Comment by knowledge-things** [comment]
@wangxinxin08 更新了2.5之后同样的模型和素材评估的MAP值全部为0甚至负数，在未更新之前有较高的识别率，只是进行大批量验证时内存溢出，会是什么原因呢。
```shell
$ python -u tools/train.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar -o use_gpu=true --eval

Done (t=0.00s)
creating index...
index created!
[10/26 13:58:23] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=0.09s).
Accumulating evaluation results...
DONE (t=0.03s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = -1.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
```

**Comment by knowledge-things** [comment]
@wangxinxin08 可以发下你在coco测试集上测试通过的版本吗？PaddlePaddle和PaddleDection的

**Comment by wangxinxin08** [comment]
> @wangxinxin08 可以发下你在coco测试集上测试通过的版本吗？PaddlePaddle和PaddleDection的

PaddlePaddle 2.3.0 PaddleDetection 2.4 CUDA 11.2，你训练没精度应该是参数没配置好吧，数据集路径或者学习率什么的

**Comment by knowledge-things** [comment]
@wangxinxin08 如果infer的时候图片尺寸和质量太大导致了out of memory有没有解决方案
尺寸4000*3000
大小10MB左右

**Comment by wangxinxin08** [comment]
解决方案已经说过了，更新最新版本，你原先训练的模型直接加载应该就能用，不用重新训练。你重新训练没有精度，应该是配置没配置好

**Comment by knowledge-things** [comment]
> 解决方案已经说过了，更新最新版本，你原先训练的模型直接加载应该就能用，不用重新训练。你重新训练没有精度，应该是配置没配置好

是的按照你的方案进行了更新，当文件超过7M大小内存就溢出了。
```shell
(paddle) root@ml:/home/kevin/workspace/PaddleDetection-dev# paddle -v
<stdin>:3: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
PaddlePaddle 2.4.0-rc0.post111, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
```

**Comment by wangxinxin08** [comment]
@knowledge-things 你上传一张4000 * 3000的图片我们试下

**Comment by knowledge-things** [comment]
> @knowledge-things 你上传一张4000 * 3000的图片我们试下

![ÉãÍ¼Íø_501421200_¸ßÑ¹µçÏßËþ£¨·ÇÆóÒµÉÌÓÃ£©](https://user-images.githubusercontent.com/7777194/198282208-5e629bf4-9fc4-4b4f-8cec-1dd5c2e20b0f.jpg)

**Comment by knowledge-things** [comment]
> @knowledge-things 你上传一张4000 * 3000的图片我们试下

链接: https://pan.baidu.com/s/1ymEJc7uS5mPRq4RjzOUnig 提取码: 1nm1 
--来自百度网盘超级会员v3的分享

**Comment by knowledge-things** [comment]
> > @knowledge-things 你上传一张4000 * 3000的图片我们试下
> 
> 我的显存是8G

**Comment by image-based-screen-industrial-detect** [comment]
> > > @knowledge-things 你上传一张4000 * 3000的图片我们试下
> > 
> > 
> > 我的显存是8G

你好，这个问题解决了么？
